-- Disposable PostgreSQL fixture for the MNTY platform-admin authorization migration.
-- This file must only run in an isolated CI database.
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE SCHEMA auth;
CREATE OR REPLACE FUNCTION auth.uid()
RETURNS uuid
LANGUAGE sql STABLE
AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
GRANT USAGE ON SCHEMA auth TO authenticated;
GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;

CREATE TABLE public.user_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  tenant_id text NOT NULL,
  status text NOT NULL,
  role text NOT NULL,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE public.mantigo_rides (
  id text PRIMARY KEY,
  customer_id uuid,
  status text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.mantigo_financial_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric NOT NULL DEFAULT 0,
  commission_amount numeric NOT NULL DEFAULT 0,
  captain_amount numeric NOT NULL DEFAULT 0,
  gross_amount numeric NOT NULL DEFAULT 0,
  captain_net_amount numeric NOT NULL DEFAULT 0,
  payment_status text,
  settlement_status text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.audit_logs (
  id text PRIMARY KEY,
  tenant_id text,
  actor_user_id uuid,
  action text,
  entity_type text,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  result text
);
CREATE TABLE public.notifications (
  id text PRIMARY KEY,
  tenant_id text,
  user_id uuid,
  type text,
  title text,
  body text,
  entity_type text,
  entity_id text
);

INSERT INTO public.user_memberships(user_id,tenant_id,status,role,permissions) VALUES
 ('11111111-1111-4111-8111-111111111111','MNTY-PLATFORM','ACTIVE','SUPER_ADMIN','{"scope":"PLATFORM","full_control":true}'),
 ('22222222-2222-4222-8222-222222222222','OTHER-TENANT','ACTIVE','OWNER','{"scope":"BUSINESS","full_control":true}'),
 ('33333333-3333-4333-8333-333333333333','MNTY-PLATFORM','INACTIVE','SUPER_ADMIN','{"scope":"PLATFORM","full_control":true}');

INSERT INTO public.mantigo_rides(id,customer_id,status,updated_at) VALUES
 ('stale-ride','44444444-4444-4444-8444-444444444444','OPEN',now()-interval '2 hours'),
 ('fresh-ride','44444444-4444-4444-8444-444444444444','OPEN',now());
INSERT INTO public.mantigo_financial_ledger(amount,commission_amount,captain_amount,gross_amount,captain_net_amount,payment_status,settlement_status,created_at)
VALUES (100,10,90,100,90,'PAID','READY',now());
