import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")??"",KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",PAYMOB_SECRET_KEY=Deno.env.get("PAYMOB_SECRET_KEY")??"",PAYMOB_INTEGRATION_ID=Deno.env.get("PAYMOB_INTEGRATION_ID")??"",PAYMOB_PUBLIC_KEY=Deno.env.get("PAYMOB_PUBLIC_KEY")??"",PAYMOB_BASE_URL=Deno.env.get("PAYMOB_BASE_URL")??"https://accept.paymob.com",CALLBACK=Deno.env.get("PAYMOB_CALLBACK_URL")??`${URL}/functions/v1/paymob-webhook`;
const admin=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const origin="https://islamnagy2022-eng.github.io";
const headers={"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...headers,"Content-Type":"application/json","Cache-Control":"no-store"}});

Deno.serve(async req=>{
 if(req.method==="OPTIONS")return json({});
 if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);
 if(req.headers.get("Origin")&&req.headers.get("Origin")!==origin)return json({error:"ORIGIN_NOT_ALLOWED"},403);
 const a=req.headers.get("Authorization");
 if(!a?.startsWith("Bearer "))return json({error:"UNAUTHORIZED"},401);
 const {data:{user},error:ae}=await admin.auth.getUser(a.slice(7));
 if(ae||!user||user.is_anonymous)return json({error:"UNAUTHORIZED"},401);
 if(!PAYMOB_SECRET_KEY||!PAYMOB_INTEGRATION_ID)return json({error:"PAYMENT_PROVIDER_NOT_CONFIGURED"},503);
 const body=await req.json().catch(()=>null) as Record<string,unknown>|null;
 const orderId=String(body?.orderId??"");
 const idem=String(body?.idempotencyKey??"");
 if(!orderId||!idem)return json({error:"INVALID_REQUEST"},400);
 const {data:o,error:oe}=await admin.from("digital_page_orders").select("id,user_id,amount,currency,payment_status,fulfillment_status,pricing_hash,provider_intent_id,title,page_type").eq("id",orderId).maybeSingle();
 if(oe||!o)return json({error:"ORDER_NOT_FOUND"},404);
 if(o.user_id!==user.id)return json({error:"FORBIDDEN"},403);
 if(o.payment_status==="PAID")return json({error:"ALREADY_PAID"},409);
 if(o.provider_intent_id)return json({orderId:o.id,status:o.payment_status,provider:"PAYMOB",clientSecret:null,checkoutUrl:null},200);
 const email=String(user.email??"").trim();
 const phone=String(user.phone??"").trim();
 if(!email||!phone)return json({error:"CUSTOMER_BILLING_CONTACT_REQUIRED"},422);
 const amount=Number(o.amount);
 if(!Number.isFinite(amount)||amount<=0)return json({error:"INVALID_AMOUNT"},409);
 const amountCents=Math.round(amount*100);
 const payload={amount:amountCents,currency:String(o.currency||"EGP").toUpperCase(),payment_methods:[Number(PAYMOB_INTEGRATION_ID)],items:[{name:o.title,amount:amountCents,description:`MantiqaTix ${o.page_type} page`,quantity:1}],billing_data:{apartment:"NA",first_name:String(user.user_metadata?.full_name||email).split(" ")[0]||"Customer",last_name:"MantiqaTix",street:"NA",building:"NA",phone_number:phone,city:"NA",country:"EG",email,floor:"NA",state:"NA"},special_reference:o.id,expiration:3600,notification_url:CALLBACK};
 const res=await fetch(`${PAYMOB_BASE_URL.replace(/\/$/,"")}/v1/intention/`,{method:"POST",headers:{"Authorization":`Token ${PAYMOB_SECRET_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});
 const p=await res.json().catch(()=>({}));
 if(!res.ok||!p?.id||!p?.client_secret)return json({error:"PAYMENT_PROVIDER_REJECTED"},502);
 const {error:ue}=await admin.from("digital_page_orders").update({provider:"PAYMOB",provider_intent_id:String(p.id),payment_status:"PENDING",updated_at:new Date().toISOString()}).eq("id",o.id).eq("payment_status","PENDING");
 if(ue)return json({error:"PAYMENT_PERSISTENCE_FAILED"},500);
 const clientSecret=String(p.client_secret);
 const checkoutUrl=PAYMOB_PUBLIC_KEY?`${PAYMOB_BASE_URL.replace(/\/$/,"")}/unifiedcheckout/?publicKey=${encodeURIComponent(PAYMOB_PUBLIC_KEY)}&clientSecret=${encodeURIComponent(clientSecret)}`:null;
 return json({orderId:o.id,status:"PENDING",provider:"PAYMOB",clientSecret,checkoutUrl,amount,currency:o.currency});
});