
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"https://islamnagy2022-eng.github.io","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,admin=createClient(URL,KEY);
async function getUser(req:Request){const a=req.headers.get("Authorization")||"";const t=a.replace(/^Bearer\s+/i,"");if(!t)return null;const r=await admin.auth.getUser(t);return r.error?null:r.data.user;}
async function isAdmin(id:string){const a=await admin.from("smm_admins").select("user_id").eq("user_id",id).maybeSingle();if(a.data)return true;const r=await admin.from("user_memberships").select("role,status").eq("user_id",id).eq("status","ACTIVE");return (r.data||[]).some((m:any)=>["OWNER","ADMIN","SUPER_ADMIN"].includes(String(m.role).toUpperCase()));}
async function secret(id:string){const r=await admin.rpc("smm_get_provider_secret",{p_provider_id:id});if(r.error||!r.data)throw new Error("Provider credential unavailable");return r.data as string;}
async function call(p:any,k:string,a:string,x:any={}){const f=new URLSearchParams();f.set("key",k);f.set("action",a);Object.entries(x).forEach(([n,v])=>f.set(n,String(v)));const r=await fetch(p.api_url,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f.toString()});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw new Error("Provider HTTP "+r.status);return d;}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const user=await getUser(req);if(!user)return json({error:"UNAUTHORIZED"},401);
 try{
  const b=await req.json(),a=b.action;
  if(a==="configure_provider"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const r=await admin.rpc("smm_set_provider_secret",{p_provider_id:b.provider_id,p_actor_user_id:user.id,p_secret:b.api_key});if(r.error)return json({error:r.error.message},400);return json({ok:true});}
  if(a==="sync_services"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const p=await admin.from("smm_providers").select("*").eq("id",b.provider_id).single();if(!p.data)return json({error:"PROVIDER_NOT_FOUND"},404);const r=await call(p.data,await secret(b.provider_id),"services");if(!Array.isArray(r))return json({error:"INVALID_PROVIDER_RESPONSE",result:r},502);let n=0;for(const s of r){const row={provider_id:b.provider_id,external_service_id:String(s.service||s.id||""),platform:String(s.platform||s.category||"Other"),category:String(s.category||"Other"),name:String(s.name||"Service"),description:String(s.description||""),provider_cost:Number(s.rate||0),selling_price:Number(s.rate||0),min_quantity:Number(s.min||1),max_quantity:Number(s.max||1000000),refill:!!s.refill,cancel:!!s.cancel,dripfeed:!!s.dripfeed,active:true,metadata:s};if(!row.external_service_id)continue;const u=await admin.from("smm_services").upsert(row,{onConflict:"provider_id,external_service_id"});if(!u.error)n++;}return json({ok:true,count:n});}
  if(a==="provider_status"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const p=await admin.from("smm_providers").select("*").eq("id",b.provider_id).single();if(!p.data)return json({error:"PROVIDER_NOT_FOUND"},404);return json({ok:true,provider:p.data.name,result:await call(p.data,await secret(b.provider_id),"balance")});}
  if(a==="admin_credit"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const ok=await admin.rpc("smm_admin_credit_wallet",{p_actor:user.id,p_user:b.user_id,p_amount:Number(b.amount),p_description:b.description||"Manual admin credit"});if(ok.error)return json({error:ok.error.message},400);return json({ok:true});}
  if(a==="admin_data"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const [p,s,o]=await Promise.all([admin.from("smm_providers").select("id,name,api_url,active,priority").order("priority"),admin.from("smm_services").select("id,provider_id,platform,category,name,provider_cost,selling_price,min_quantity,max_quantity,active").order("created_at",{ascending:false}).limit(200),admin.from("smm_orders").select("id,user_id,service_id,quantity,selling_price,profit,status,provider_order_id,created_at").order("created_at",{ascending:false}).limit(100)]);return json({providers:p.data||[],services:s.data||[],orders:o.data||[]});}
  if(a==="set_price"){if(!(await isAdmin(user.id)))return json({error:"FORBIDDEN"},403);const price=Number(b.selling_price);if(!Number.isFinite(price)||price<0)return json({error:"INVALID_PRICE"},400);const r=await admin.from("smm_services").update({selling_price:price,updated_at:new Date().toISOString()}).eq("id",b.service_id);if(r.error)return json({error:r.error.message},400);return json({ok:true});}
  if(a==="place_order"){const q=Number(b.quantity);if(!b.service_id||!b.target_url||!Number.isInteger(q)||q<=0)return json({error:"INVALID_ORDER"},400);const s=await admin.from("smm_services").select("*,smm_providers(*)").eq("id",b.service_id).eq("active",true).single();if(!s.data)return json({error:"SERVICE_NOT_FOUND"},404);const v=s.data;if(q<v.min_quantity||q>v.max_quantity)return json({error:"QUANTITY_OUT_OF_RANGE",min:v.min_quantity,max:v.max_quantity},400);const sell=Number(v.selling_price)*q/1000,cost=Number(v.provider_cost)*q/1000;const o=await admin.from("smm_orders").insert({user_id:user.id,service_id:b.service_id,target_url:b.target_url,quantity:q,selling_price:sell,provider_cost:cost,profit:sell-cost,status:"SUBMITTING"}).select("*").single();if(o.error)return json({error:o.error.message},400);const debit=await admin.rpc("smm_debit_wallet",{p_user:user.id,p_amount:sell,p_reference:o.data.id});if(debit.error||debit.data!==true){await admin.from("smm_orders").update({status:"FAILED",error_message:"Insufficient wallet balance"}).eq("id",o.data.id);return json({error:"INSUFFICIENT_BALANCE",required:sell,order_id:o.data.id},402);}try{const r=await call(v.smm_providers,await secret(v.provider_id),"add",{service:v.external_service_id,link:b.target_url,quantity:q}),pid=r.order??r.order_id;if(!pid)throw new Error("Provider did not return an order id");await admin.from("smm_orders").update({status:"PROCESSING",provider_order_id:String(pid),provider_status:"submitted",updated_at:new Date().toISOString()}).eq("id",o.data.id);await admin.from("smm_order_events").insert({order_id:o.data.id,event_type:"SUBMITTED",payload:r});return json({ok:true,order_id:o.data.id,provider_order_id:String(pid),status:"PROCESSING",charged:sell});}catch(e){const m=e instanceof Error?e.message:"Provider error";await admin.rpc("smm_refund_wallet",{p_user:user.id,p_amount:sell,p_reference:o.data.id,p_description:"Automatic refund after provider failure"});await admin.from("smm_orders").update({status:"FAILED",error_message:m,updated_at:new Date().toISOString()}).eq("id",o.data.id);return json({error:"PROVIDER_EXECUTION_FAILED",message:m,order_id:o.data.id},502);}}
  if(a==="order_status"){const o=await admin.from("smm_orders").select("*,smm_services(*,smm_providers(*))").eq("id",b.order_id).eq("user_id",user.id).single();if(!o.data)return json({error:"ORDER_NOT_FOUND"},404);if(!o.data.provider_order_id)return json({ok:true,status:o.data.status});const r=await call(o.data.smm_services.smm_providers,await secret(o.data.smm_services.provider_id),"status",{order:o.data.provider_order_id}),m=String(r.status||"").toLowerCase();let st=o.data.status;if(["completed","complete"].includes(m))st="COMPLETED";else if(m==="partial")st="PARTIAL";else if(["canceled","cancelled"].includes(m))st="CANCELLED";else if(["processing","in progress","inprogress"].includes(m))st="PROCESSING";await admin.from("smm_orders").update({status:st,provider_status:r.status??null,updated_at:new Date().toISOString()}).eq("id",b.order_id);await admin.from("smm_order_events").insert({order_id:b.order_id,event_type:"STATUS_SYNC",payload:r});return json({ok:true,status:st,result:r});}
  return json({error:"UNKNOWN_ACTION"},400);
 }catch(e){return json({error:e instanceof Error?e.message:"INTERNAL_ERROR"},500);}
});