-- RC339: official MantiqatiX platform-managed showcase seed.
-- Applied to production as rc339_seed_mantiqati_official_showcase.
-- Safe/idempotent seed scoped to MNTY-PLATFORM; no auth users are created.
begin;
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.business_sectors(id,code,name_ar,name_en,status) select 'SEC-'||code,code,name_ar,name_en,'ACTIVE' from seed
on conflict (id) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,status='ACTIVE';
with seed(code,name_ar,name_en) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX'),('LABS','معمل منطقتي','Lab MantiqatiX'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX'),('DENTAL','أسنان منطقتي','Dental MantiqatiX'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX'),('FASHION','أزياء منطقتي','Fashion MantiqatiX'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX'),('COMPANIES','شركة منطقتي','Company MantiqatiX'),('EDUCATION','مدرسة منطقتي','School MantiqatiX'),('ERP','برمجيات منطقتي','Software MantiqatiX'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX'),('TRIPS','سفر منطقتي','Travel MantiqatiX'),('MANTIGO','نقل منطقتي','Transport MantiqatiX'),('JOBS','وظائف منطقتي','Jobs MantiqatiX'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX'),('AUTO','سيارات منطقتي','Auto MantiqatiX'),('SPORTS','رياضة منطقتي','Sports MantiqatiX'))
insert into public.business_categories(id,sector_id,code,name_ar,name_en,status) select 'CAT-'||code,'SEC-'||code,code,name_ar,name_en,'ACTIVE' from seed
on conflict (id) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,status='ACTIVE';
with seed(code,name_ar,description) as (values ('CONTROL','التحكم الكامل','إدارة الأنشطة والفروع والخدمات والاعتمادات'),('HOME','الرئيسية','لوحة التحكم الموحدة'),('MODULES','الموديولات','تشغيل وإدارة وحدات المنصة'),('DOMAINS','المجالات والخدمات','القطاعات ومقدمو الخدمات'),('FASHION','التجارة والأزياء','المنتجات والمقاسات والسلة والطلبات'),('GROCERY','البقالة والسوبر ماركت','المنتجات والمخزون والطلبات'),('RESTAURANTS','المطاعم والمطابخ','القوائم والإضافات والمطبخ والتوصيل'),('MEDICAL','المنظومة الطبية','الأطباء والعيادات والصيدليات والمعامل والأشعة والمستشفيات'),('MAINTENANCE','الصيانة','طلبات الصيانة ومقدمو الخدمة'),('PRO_SERVICES','الخدمات المهنية','المحاسبة والقانون والشركات والبرمجيات والتسويق'),('MANTIGO','MantiGO والنقل','الطلبات والعروض والرحلات والتنفيذ'),('MATRIMONY','الزواج','الملفات والترشيحات والتواصل'),('JOBS','الوظائف','الوظائف والمتقدمون والمقابلات'),('EDUCATION','التعليم','المدارس والمدرسون والحجوزات'),('USED_ITEMS','المستعمل','الإعلانات والعروض والتفاوض'),('MARKETING','التسويق والإعلان','التسويق الداخلي وشركات التسويق والعملاء المحتملون'),('SMM','خدمات التسويق الرقمي SMM','الخدمات والموردون والطلبات والتتبع'),('CRM','المستخدمون وCRM','العملاء ومقدمو الخدمة والمتابعة والاحتفاظ'),('OPERATIONS','الطلبات والعمليات','الطلبات والحجوزات وسير التنفيذ'),('FINANCE','العمولات والباقات','العمولات والاشتراكات والباقات'),('ANALYTICS','التقارير والتحليلات','الأداء والتحويلات والإيرادات والمخاطر'),('GOVERNANCE','الدعم والحوكمة','التذاكر والتدقيق والصلاحيات والمراقبة'),('REGISTRATION','طلبات التسجيل','اعتماد طلبات العملاء ومقدمي الخدمة'),('SETTINGS','الإعدادات','الحساب والمنصة والتفضيلات'))
insert into public.modules(id,code,name,description,status,version,configuration) select 'MOD-'||code,code,name_ar,description,'ACTIVE','1.0.0','{}'::jsonb from seed
on conflict (id) do update set name=excluded.name,description=excluded.description,status='ACTIVE';
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.businesses(id,tenant_id,organization_id,name,code,status,settings)
select md5('MNTY-SHOWCASE-'||code)::uuid,'MNTY-PLATFORM','MNTY-MAIN',name_ar,'MNTY-'||code,'INACTIVE',
jsonb_build_object('showcase',true,'managed_by','SUPER_ADMIN','brand','MantiqatiX','activity_code',code,'display_name_ar',name_ar,'icon',icon,'icon_asset_ref','assets/activities/'||lower(code)||'.svg','headline',description,'category_code',code,'location_label','منطقتي','profile_complete',true,'source','OFFICIAL_PLATFORM_SHOWCASE')
from seed on conflict (id) do update set name=excluded.name,code=excluded.code,settings=excluded.settings,updated_at=now();
with seed(code) as (values ('HEALTH'),('PHARMACY'),('LABS'),('RADIOLOGY'),('HOSPITAL'),('DENTAL'),('VETERINARY'),('FOOD'),('GROCERY'),('FASHION'),('MAINTENANCE'),('ACCOUNTING'),('LEGAL'),('COMPANIES'),('EDUCATION'),('ERP'),('MARKETING'),('TRIPS'),('MANTIGO'),('JOBS'),('MATRIMONY'),('USED_ITEMS'),('REAL_ESTATE'),('AUTO'),('SPORTS'))
insert into public.user_memberships(id,user_id,tenant_id,organization_id,business_id,branch_id,role,permissions,status)
select 'SHOWCASE-OWNER-'||s.code,'f7914ac7-4b03-4456-afdd-e386f2ac6a5b','MNTY-PLATFORM','MNTY-MAIN',b.id,null,'OWNER','{"showcase_manage":true,"modules_manage":true,"profile_manage":true,"content_manage":true}'::jsonb,'ACTIVE'
from seed s join public.businesses b on b.code='MNTY-'||s.code
on conflict (id) do update set business_id=excluded.business_id,role='OWNER',status='ACTIVE',permissions=excluded.permissions;
update public.businesses b set status='ACTIVE',updated_at=now()
where b.tenant_id='MNTY-PLATFORM' and b.settings->>'showcase'='true' and exists(select 1 from public.user_memberships m where m.business_id=b.id and m.user_id='f7914ac7-4b03-4456-afdd-e386f2ac6a5b'::uuid and m.role in ('OWNER','BUSINESS_OWNER') and m.status='ACTIVE');
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.marketing_provider_profiles(provider_kind,business_id,owner_user_id,name_ar,name_en,slug,description,specialties,service_areas,portfolio,status,is_verified,is_featured,ranking_weight,settings,profile_image_path)
select 'OFFICIAL',b.id,'f7914ac7-4b03-4456-afdd-e386f2ac6a5b',s.name_ar,s.name_en,'mantiqati-'||lower(s.code),s.description,jsonb_build_array(s.description,'حجز وطلب خدمة','متابعة الطلب','خدمة عملاء'),'["منطقتي"]'::jsonb,jsonb_build_array(jsonb_build_object('type','brand_icon','asset','assets/activities/'||lower(s.code)||'.svg','title','هوية '||s.name_ar)),'ACTIVE',true,true,100,jsonb_build_object('official_showcase',true,'managed_by','SUPER_ADMIN','brand','MantiqatiX','icon',s.icon,'location_label','منطقتي'),'assets/activities/'||lower(s.code)||'.svg'
from seed s join public.businesses b on b.code='MNTY-'||s.code
on conflict (slug) do update set business_id=excluded.business_id,owner_user_id=excluded.owner_user_id,name_ar=excluded.name_ar,name_en=excluded.name_en,description=excluded.description,status='ACTIVE',is_verified=true,is_featured=true,ranking_weight=100,settings=excluded.settings,profile_image_path=excluded.profile_image_path;
with seed(code,name_ar,name_en,description) as (values ('HEALTH','خدمة دكتور منطقتي','Doctor MantiqatiX Primary Service','خدمات طبية وحجوزات واستشارات'),('PHARMACY','خدمة صيدلية منطقتي','Pharmacy MantiqatiX Primary Service','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','خدمة معمل منطقتي','Lab MantiqatiX Primary Service','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','خدمة أشعة منطقتي','Radiology MantiqatiX Primary Service','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','خدمة مستشفى منطقتي','Hospital MantiqatiX Primary Service','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','خدمة أسنان منطقتي','Dental MantiqatiX Primary Service','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','خدمة بيطري منطقتي','Veterinary MantiqatiX Primary Service','رعاية وعلاج وخدمات بيطرية'),('FOOD','خدمة مطعم منطقتي','Restaurant MantiqatiX Primary Service','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','خدمة سوبر ماركت منطقتي','Supermarket MantiqatiX Primary Service','منتجات وبقالة ومخزون وطلبات'),('FASHION','خدمة أزياء منطقتي','Fashion MantiqatiX Primary Service','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','خدمة صيانة منطقتي','Maintenance MantiqatiX Primary Service','صيانة منزلية وخدمات فنية'),('ACCOUNTING','خدمة محاسب منطقتي','Accountant MantiqatiX Primary Service','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','خدمة محامي منطقتي','Lawyer MantiqatiX Primary Service','استشارات ووثائق وخدمات قانونية'),('COMPANIES','خدمة شركة منطقتي','Company MantiqatiX Primary Service','خدمات أعمال وموردون وشراكات'),('EDUCATION','خدمة مدرسة منطقتي','School MantiqatiX Primary Service','تعليم ودروس وتدريب وحجوزات'),('ERP','خدمة برمجيات منطقتي','Software MantiqatiX Primary Service','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','خدمة تسويق منطقتي','Marketing MantiqatiX Primary Service','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','خدمة سفر منطقتي','Travel MantiqatiX Primary Service','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','خدمة نقل منطقتي','Transport MantiqatiX Primary Service','نقل وطلبات رحلات وعروض'),('JOBS','خدمة وظائف منطقتي','Jobs MantiqatiX Primary Service','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','خدمة زواج منطقتي','Matrimony MantiqatiX Primary Service','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','خدمة مستعمل منطقتي','Used Items MantiqatiX Primary Service','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','خدمة عقارات منطقتي','Real Estate MantiqatiX Primary Service','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','خدمة سيارات منطقتي','Auto MantiqatiX Primary Service','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','خدمة رياضة منطقتي','Sports MantiqatiX Primary Service','أندية ومدربون وبرامج لياقة'))
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) select 'MNTY_'||code||'_PRIMARY',name_ar,name_en,code,'الخدمة الرسمية الأساسية — '||description,'ACTIVE' from seed
on conflict (code) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,category_code=excluded.category_code,description=excluded.description,status='ACTIVE';
with seed(code) as (values ('HEALTH'),('PHARMACY'),('LABS'),('RADIOLOGY'),('HOSPITAL'),('DENTAL'),('VETERINARY'),('FOOD'),('GROCERY'),('FASHION'),('MAINTENANCE'),('ACCOUNTING'),('LEGAL'),('COMPANIES'),('EDUCATION'),('ERP'),('MARKETING'),('TRIPS'),('MANTIGO'),('JOBS'),('MATRIMONY'),('USED_ITEMS'),('REAL_ESTATE'),('AUTO'),('SPORTS'))
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status)
select p.id,s.id,'الخدمة الرسمية الأساسية للنشاط',0,0,'EGP','ACTIVE' from seed x join public.marketing_provider_profiles p on p.slug='mantiqati-'||lower(x.code) join public.marketing_services s on s.code='MNTY_'||x.code||'_PRIMARY'
on conflict (provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.business_modules(id,business_id,module_id,enabled,configuration)
select 'BM-SHOWCASE-'||b.code||'-'||m.code,b.id,m.id,true,jsonb_build_object('managed_by','SUPER_ADMIN','showcase',true,'activity_code',b.settings->>'activity_code')
from public.businesses b cross join public.modules m where b.tenant_id='MNTY-PLATFORM' and b.settings->>'showcase'='true'
on conflict (business_id,module_id) do update set enabled=true,configuration=excluded.configuration,updated_at=now();
drop policy if exists "Public can view official showcase businesses" on public.businesses;
create policy "Public can view official showcase businesses" on public.businesses for select to anon,authenticated using (status='ACTIVE' and coalesce(settings->>'showcase','false')='true');
commit;


-- RC339 enrichment: sector-specific specialties, portfolio entries and service catalog.
begin;
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HEALTH_A','كشف طبي','كشف طبي','HEALTH','خدمة رسمية ضمن HEALTH — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة كشف طبي — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HEALTH_A' where p.slug='mantiqati-health' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HEALTH_B','استشارة طبية','استشارة طبية','HEALTH','خدمة رسمية ضمن HEALTH — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة استشارة طبية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HEALTH_B' where p.slug='mantiqati-health' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HEALTH_C','متابعة حالة','متابعة حالة','HEALTH','خدمة رسمية ضمن HEALTH — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة متابعة حالة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HEALTH_C' where p.slug='mantiqati-health' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_PHARMACY_A','طلب صيدلية','طلب صيدلية','PHARMACY','خدمة رسمية ضمن PHARMACY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة طلب صيدلية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_PHARMACY_A' where p.slug='mantiqati-pharmacy' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_PHARMACY_B','تجهيز طلب','تجهيز طلب','PHARMACY','خدمة رسمية ضمن PHARMACY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تجهيز طلب — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_PHARMACY_B' where p.slug='mantiqati-pharmacy' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_PHARMACY_C','توصيل','توصيل','PHARMACY','خدمة رسمية ضمن PHARMACY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة توصيل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_PHARMACY_C' where p.slug='mantiqati-pharmacy' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LABS_A','تحاليل مخبرية','تحاليل مخبرية','LABS','خدمة رسمية ضمن LABS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تحاليل مخبرية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LABS_A' where p.slug='mantiqati-labs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LABS_B','سحب عينات','سحب عينات','LABS','خدمة رسمية ضمن LABS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة سحب عينات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LABS_B' where p.slug='mantiqati-labs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LABS_C','حجز فحوصات','حجز فحوصات','LABS','خدمة رسمية ضمن LABS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة حجز فحوصات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LABS_C' where p.slug='mantiqati-labs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_RADIOLOGY_A','أشعة','أشعة','RADIOLOGY','خدمة رسمية ضمن RADIOLOGY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة أشعة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_RADIOLOGY_A' where p.slug='mantiqati-radiology' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_RADIOLOGY_B','موجات صوتية','موجات صوتية','RADIOLOGY','خدمة رسمية ضمن RADIOLOGY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة موجات صوتية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_RADIOLOGY_B' where p.slug='mantiqati-radiology' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_RADIOLOGY_C','حجز فحص','حجز فحص','RADIOLOGY','خدمة رسمية ضمن RADIOLOGY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة حجز فحص — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_RADIOLOGY_C' where p.slug='mantiqati-radiology' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HOSPITAL_A','حجز عيادة','حجز عيادة','HOSPITAL','خدمة رسمية ضمن HOSPITAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة حجز عيادة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HOSPITAL_A' where p.slug='mantiqati-hospital' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HOSPITAL_B','متابعة','متابعة','HOSPITAL','خدمة رسمية ضمن HOSPITAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة متابعة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HOSPITAL_B' where p.slug='mantiqati-hospital' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_HOSPITAL_C','خدمات رعاية','خدمات رعاية','HOSPITAL','خدمة رسمية ضمن HOSPITAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة خدمات رعاية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_HOSPITAL_C' where p.slug='mantiqati-hospital' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_DENTAL_A','كشف أسنان','كشف أسنان','DENTAL','خدمة رسمية ضمن DENTAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة كشف أسنان — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_DENTAL_A' where p.slug='mantiqati-dental' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_DENTAL_B','علاج وتنظيف','علاج وتنظيف','DENTAL','خدمة رسمية ضمن DENTAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة علاج وتنظيف — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_DENTAL_B' where p.slug='mantiqati-dental' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_DENTAL_C','تركيبات وتقويم','تركيبات وتقويم','DENTAL','خدمة رسمية ضمن DENTAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تركيبات وتقويم — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_DENTAL_C' where p.slug='mantiqati-dental' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_VETERINARY_A','كشف بيطري','كشف بيطري','VETERINARY','خدمة رسمية ضمن VETERINARY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة كشف بيطري — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_VETERINARY_A' where p.slug='mantiqati-veterinary' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_VETERINARY_B','تطعيمات','تطعيمات','VETERINARY','خدمة رسمية ضمن VETERINARY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تطعيمات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_VETERINARY_B' where p.slug='mantiqati-veterinary' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_VETERINARY_C','متابعة','متابعة','VETERINARY','خدمة رسمية ضمن VETERINARY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة متابعة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_VETERINARY_C' where p.slug='mantiqati-veterinary' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FOOD_A','طلب طعام','طلب طعام','FOOD','خدمة رسمية ضمن FOOD — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة طلب طعام — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FOOD_A' where p.slug='mantiqati-food' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FOOD_B','وجبات وعروض','وجبات وعروض','FOOD','خدمة رسمية ضمن FOOD — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة وجبات وعروض — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FOOD_B' where p.slug='mantiqati-food' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FOOD_C','توصيل','توصيل','FOOD','خدمة رسمية ضمن FOOD — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة توصيل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FOOD_C' where p.slug='mantiqati-food' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_GROCERY_A','طلب بقالة','طلب بقالة','GROCERY','خدمة رسمية ضمن GROCERY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة طلب بقالة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_GROCERY_A' where p.slug='mantiqati-grocery' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_GROCERY_B','تجهيز طلب','تجهيز طلب','GROCERY','خدمة رسمية ضمن GROCERY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تجهيز طلب — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_GROCERY_B' where p.slug='mantiqati-grocery' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_GROCERY_C','توصيل','توصيل','GROCERY','خدمة رسمية ضمن GROCERY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة توصيل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_GROCERY_C' where p.slug='mantiqati-grocery' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FASHION_A','منتجات أزياء','منتجات أزياء','FASHION','خدمة رسمية ضمن FASHION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة منتجات أزياء — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FASHION_A' where p.slug='mantiqati-fashion' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FASHION_B','تفصيل وتعديل','تفصيل وتعديل','FASHION','خدمة رسمية ضمن FASHION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تفصيل وتعديل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FASHION_B' where p.slug='mantiqati-fashion' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_FASHION_C','طلبات','طلبات','FASHION','خدمة رسمية ضمن FASHION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة طلبات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_FASHION_C' where p.slug='mantiqati-fashion' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MAINTENANCE_A','كهرباء','كهرباء','MAINTENANCE','خدمة رسمية ضمن MAINTENANCE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة كهرباء — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MAINTENANCE_A' where p.slug='mantiqati-maintenance' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MAINTENANCE_B','سباكة','سباكة','MAINTENANCE','خدمة رسمية ضمن MAINTENANCE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة سباكة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MAINTENANCE_B' where p.slug='mantiqati-maintenance' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MAINTENANCE_C','تكييف','تكييف','MAINTENANCE','خدمة رسمية ضمن MAINTENANCE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تكييف — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MAINTENANCE_C' where p.slug='mantiqati-maintenance' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ACCOUNTING_A','مسك دفاتر','مسك دفاتر','ACCOUNTING','خدمة رسمية ضمن ACCOUNTING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مسك دفاتر — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ACCOUNTING_A' where p.slug='mantiqati-accounting' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ACCOUNTING_B','مراجعة حسابات','مراجعة حسابات','ACCOUNTING','خدمة رسمية ضمن ACCOUNTING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مراجعة حسابات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ACCOUNTING_B' where p.slug='mantiqati-accounting' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ACCOUNTING_C','استشارات مالية','استشارات مالية','ACCOUNTING','خدمة رسمية ضمن ACCOUNTING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة استشارات مالية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ACCOUNTING_C' where p.slug='mantiqati-accounting' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LEGAL_A','استشارة قانونية','استشارة قانونية','LEGAL','خدمة رسمية ضمن LEGAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة استشارة قانونية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LEGAL_A' where p.slug='mantiqati-legal' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LEGAL_B','صياغة مستندات','صياغة مستندات','LEGAL','خدمة رسمية ضمن LEGAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة صياغة مستندات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LEGAL_B' where p.slug='mantiqati-legal' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_LEGAL_C','مراجعة عقود','مراجعة عقود','LEGAL','خدمة رسمية ضمن LEGAL — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مراجعة عقود — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_LEGAL_C' where p.slug='mantiqati-legal' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_COMPANIES_A','خدمات أعمال','خدمات أعمال','COMPANIES','خدمة رسمية ضمن COMPANIES — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة خدمات أعمال — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_COMPANIES_A' where p.slug='mantiqati-companies' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_COMPANIES_B','توريد','توريد','COMPANIES','خدمة رسمية ضمن COMPANIES — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة توريد — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_COMPANIES_B' where p.slug='mantiqati-companies' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_COMPANIES_C','شراكات','شراكات','COMPANIES','خدمة رسمية ضمن COMPANIES — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة شراكات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_COMPANIES_C' where p.slug='mantiqati-companies' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_EDUCATION_A','دروس','دروس','EDUCATION','خدمة رسمية ضمن EDUCATION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة دروس — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_EDUCATION_A' where p.slug='mantiqati-education' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_EDUCATION_B','تدريب','تدريب','EDUCATION','خدمة رسمية ضمن EDUCATION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تدريب — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_EDUCATION_B' where p.slug='mantiqati-education' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_EDUCATION_C','حجز حصص','حجز حصص','EDUCATION','خدمة رسمية ضمن EDUCATION — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة حجز حصص — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_EDUCATION_C' where p.slug='mantiqati-education' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ERP_A','تطوير برمجيات','تطوير برمجيات','ERP','خدمة رسمية ضمن ERP — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تطوير برمجيات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ERP_A' where p.slug='mantiqati-erp' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ERP_B','مواقع','مواقع','ERP','خدمة رسمية ضمن ERP — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مواقع — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ERP_B' where p.slug='mantiqati-erp' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_ERP_C','دعم تقني','دعم تقني','ERP','خدمة رسمية ضمن ERP — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة دعم تقني — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_ERP_C' where p.slug='mantiqati-erp' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MARKETING_A','إدارة حملات','إدارة حملات','MARKETING','خدمة رسمية ضمن MARKETING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة إدارة حملات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MARKETING_A' where p.slug='mantiqati-marketing' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MARKETING_B','محتوى','محتوى','MARKETING','خدمة رسمية ضمن MARKETING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة محتوى — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MARKETING_B' where p.slug='mantiqati-marketing' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MARKETING_C','إعلانات رقمية','إعلانات رقمية','MARKETING','خدمة رسمية ضمن MARKETING — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة إعلانات رقمية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MARKETING_C' where p.slug='mantiqati-marketing' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_TRIPS_A','برامج سياحية','برامج سياحية','TRIPS','خدمة رسمية ضمن TRIPS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة برامج سياحية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_TRIPS_A' where p.slug='mantiqati-trips' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_TRIPS_B','حجوزات','حجوزات','TRIPS','خدمة رسمية ضمن TRIPS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة حجوزات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_TRIPS_B' where p.slug='mantiqati-trips' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_TRIPS_C','رحلات','رحلات','TRIPS','خدمة رسمية ضمن TRIPS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة رحلات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_TRIPS_C' where p.slug='mantiqati-trips' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MANTIGO_A','طلبات نقل','طلبات نقل','MANTIGO','خدمة رسمية ضمن MANTIGO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة طلبات نقل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MANTIGO_A' where p.slug='mantiqati-mantigo' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MANTIGO_B','رحلات','رحلات','MANTIGO','خدمة رسمية ضمن MANTIGO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة رحلات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MANTIGO_B' where p.slug='mantiqati-mantigo' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MANTIGO_C','توصيل','توصيل','MANTIGO','خدمة رسمية ضمن MANTIGO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة توصيل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MANTIGO_C' where p.slug='mantiqati-mantigo' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_JOBS_A','نشر وظائف','نشر وظائف','JOBS','خدمة رسمية ضمن JOBS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة نشر وظائف — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_JOBS_A' where p.slug='mantiqati-jobs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_JOBS_B','بحث مرشحين','بحث مرشحين','JOBS','خدمة رسمية ضمن JOBS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة بحث مرشحين — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_JOBS_B' where p.slug='mantiqati-jobs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_JOBS_C','مقابلات','مقابلات','JOBS','خدمة رسمية ضمن JOBS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مقابلات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_JOBS_C' where p.slug='mantiqati-jobs' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MATRIMONY_A','ملفات تعريف','ملفات تعريف','MATRIMONY','خدمة رسمية ضمن MATRIMONY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة ملفات تعريف — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MATRIMONY_A' where p.slug='mantiqati-matrimony' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MATRIMONY_B','ترشيحات','ترشيحات','MATRIMONY','خدمة رسمية ضمن MATRIMONY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة ترشيحات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MATRIMONY_B' where p.slug='mantiqati-matrimony' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_MATRIMONY_C','إدارة طلبات','إدارة طلبات','MATRIMONY','خدمة رسمية ضمن MATRIMONY — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة إدارة طلبات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_MATRIMONY_C' where p.slug='mantiqati-matrimony' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_USED_ITEMS_A','إعلانات مستعمل','إعلانات مستعمل','USED_ITEMS','خدمة رسمية ضمن USED_ITEMS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة إعلانات مستعمل — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_USED_ITEMS_A' where p.slug='mantiqati-used_items' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_USED_ITEMS_B','بحث منتجات','بحث منتجات','USED_ITEMS','خدمة رسمية ضمن USED_ITEMS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة بحث منتجات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_USED_ITEMS_B' where p.slug='mantiqati-used_items' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_USED_ITEMS_C','تفاوض','تفاوض','USED_ITEMS','خدمة رسمية ضمن USED_ITEMS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تفاوض — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_USED_ITEMS_C' where p.slug='mantiqati-used_items' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_REAL_ESTATE_A','بيع عقارات','بيع عقارات','REAL_ESTATE','خدمة رسمية ضمن REAL_ESTATE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة بيع عقارات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_REAL_ESTATE_A' where p.slug='mantiqati-real_estate' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_REAL_ESTATE_B','إيجار','إيجار','REAL_ESTATE','خدمة رسمية ضمن REAL_ESTATE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة إيجار — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_REAL_ESTATE_B' where p.slug='mantiqati-real_estate' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_REAL_ESTATE_C','تسويق عقاري','تسويق عقاري','REAL_ESTATE','خدمة رسمية ضمن REAL_ESTATE — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة تسويق عقاري — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_REAL_ESTATE_C' where p.slug='mantiqati-real_estate' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_AUTO_A','بيع سيارات','بيع سيارات','AUTO','خدمة رسمية ضمن AUTO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة بيع سيارات — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_AUTO_A' where p.slug='mantiqati-auto' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_AUTO_B','فحص','فحص','AUTO','خدمة رسمية ضمن AUTO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة فحص — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_AUTO_B' where p.slug='mantiqati-auto' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_AUTO_C','صيانة','صيانة','AUTO','خدمة رسمية ضمن AUTO — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة صيانة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_AUTO_C' where p.slug='mantiqati-auto' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_SPORTS_A','أندية','أندية','SPORTS','خدمة رسمية ضمن SPORTS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة أندية — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_SPORTS_A' where p.slug='mantiqati-sports' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_SPORTS_B','مدربون','مدربون','SPORTS','خدمة رسمية ضمن SPORTS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة مدربون — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_SPORTS_B' where p.slug='mantiqati-sports' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) values('MNTY_SPORTS_C','برامج لياقة','برامج لياقة','SPORTS','خدمة رسمية ضمن SPORTS — مُدارة من منصة منطقتي','ACTIVE') on conflict(code) do update set name_ar=excluded.name_ar,description=excluded.description,status='ACTIVE';
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status) select p.id,s.id,'خدمة برامج لياقة — بدون سعر افتراضي حتى يتم اعتماد التسعير',null,null,'EGP','ACTIVE' from public.marketing_provider_profiles p join public.marketing_services s on s.code='MNTY_SPORTS_C' where p.slug='mantiqati-sports' on conflict(provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
commit;
