-- Restrict sensitive/member/financial RLS policies to authenticated users.
-- Existing USING/WITH CHECK expressions are preserved.
alter policy advertisements_manager_delete on public.advertisements to authenticated;
alter policy advertisements_manager_update on public.advertisements to authenticated;
alter policy advertisements_member_read on public.advertisements to authenticated;
alter policy approval_actions_member_read on public.approval_actions to authenticated;
alter policy approval_requests_manager_update on public.approval_requests to authenticated;
alter policy approval_requests_scoped_read on public.approval_requests to authenticated;
alter policy audit_logs_select_tenant on public.audit_logs to authenticated;
alter policy business_modules_manager_delete on public.business_modules to authenticated;
alter policy business_modules_manager_update on public.business_modules to authenticated;
alter policy business_modules_member_read on public.business_modules to authenticated;
alter policy business_referral_codes_member_read on public.business_referral_codes to authenticated;
alter policy business_referral_events_member_read on public.business_referral_events to authenticated;
alter policy business_subscriptions_owner_select on public.business_subscriptions to authenticated;
alter policy chart_of_accounts_member_read on public.chart_of_accounts to authenticated;
alter policy commission_rules_admin_delete on public.commission_rules to authenticated;
alter policy commission_rules_admin_update on public.commission_rules to authenticated;
alter policy commission_rules_member_read on public.commission_rules to authenticated;
alter policy commission_transactions_finance_read on public.commission_transactions to authenticated;
alter policy credit_accounts_finance_read on public.credit_accounts to authenticated;
alter policy credit_periods_finance_read on public.credit_periods to authenticated;
alter policy departments_manager_write on public.departments to authenticated;
alter policy departments_member_read on public.departments to authenticated;
alter policy general_ledger_finance_read on public.general_ledger to authenticated;
alter policy inventory_transactions_member_read on public.inventory_transactions to authenticated;
alter policy journal_entries_finance_read on public.journal_entries to authenticated;
alter policy journal_entries_manager_update on public.journal_entries to authenticated;
alter policy journal_entry_lines_finance_read on public.journal_entry_lines to authenticated;
alter policy "Authenticated can view active commission rules" on public.marketing_commission_rules to authenticated;
alter policy "Users view own marketing leads" on public.marketing_leads to authenticated;
alter policy "Providers view assigned projects" on public.marketing_project_participants to authenticated;
alter policy "Project clients can view own marketing projects" on public.marketing_projects to authenticated;
alter policy "Owners view their subscriptions" on public.marketing_provider_subscriptions to authenticated;
alter policy modules_authenticated_read on public.modules to authenticated;
alter policy notifications_select_own on public.notifications to authenticated;
alter policy notifications_update_own on public.notifications to authenticated;
alter policy order_status_history_member_read on public.order_status_history to authenticated;
alter policy payment_events_finance_read on public.payment_events to authenticated;
alter policy payment_financial_reconciliations_finance_read on public.payment_financial_reconciliations to authenticated;
alter policy payment_intents_finance_read on public.payment_intents to authenticated;
alter policy payment_provider_events_finance_read on public.payment_provider_events to authenticated;
alter policy feature_flags_read_member on public.platform_feature_flags to authenticated;
alter policy feature_flags_write_admin on public.platform_feature_flags to authenticated;
alter policy referral_codes_self_read on public.referral_codes to authenticated;
alter policy referral_events_self_read on public.referral_events to authenticated;
alter policy refund_transactions_finance_select on public.refund_transactions to authenticated;
alter policy settlement_attempts_finance_read on public.settlement_attempts to authenticated;
alter policy settlement_transactions_finance_read on public.settlement_transactions to authenticated;
alter policy smm_order_events_owner_read on public.smm_order_events to authenticated;
alter policy smm_orders_owner_read on public.smm_orders to authenticated;
alter policy smm_wallet_tx_owner_read on public.smm_wallet_transactions to authenticated;
alter policy smm_wallet_owner_read on public.smm_wallets to authenticated;
alter policy stock_balances_member_read on public.stock_balances to authenticated;
alter policy subscription_payment_intents_owner_read on public.subscription_payment_intents to authenticated;
alter policy support_tickets_select_member on public.support_tickets to authenticated;
alter policy support_tickets_update_staff on public.support_tickets to authenticated;
alter policy sync_logs_select_tenant on public.sync_logs to authenticated;
alter policy tenant_modules_admin_delete on public.tenant_modules to authenticated;
alter policy tenant_modules_admin_update on public.tenant_modules to authenticated;
alter policy tenant_modules_member_read on public.tenant_modules to authenticated;
alter policy tenant_payment_methods_manage on public.tenant_payment_methods to authenticated;
alter policy ticket_messages_select_member on public.ticket_messages to authenticated;
alter policy wallet_accounts_finance_read on public.wallet_accounts to authenticated;
alter policy wallet_transactions_finance_read on public.wallet_transactions to authenticated;
alter policy warehouses_manager_delete on public.warehouses to authenticated;
alter policy warehouses_manager_update on public.warehouses to authenticated;
alter policy warehouses_member_read on public.warehouses to authenticated;
