-- RC339: official MantiqatiX platform-managed showcase seed.
-- Applied to production as rc339_seed_mantiqati_official_showcase.
-- Safe/idempotent seed scoped to MNTY-PLATFORM; no auth users are created.
begin;
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.business_sectors(id,code,name_ar,name_en,status) select 'SEC-'||code,code,name_ar,name_en,'ACTIVE' from seed
on conflict (id) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,status='ACTIVE';
with seed(code,name_ar,name_en) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX'),('LABS','معمل منطقتي','Lab MantiqatiX'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX'),('DENTAL','أسنان منطقتي','Dental MantiqatiX'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX'),('FASHION','أزياء منطقتي','Fashion MantiqatiX'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX'),('COMPANIES','شركة منطقتي','Company MantiqatiX'),('EDUCATION','مدرسة منطقتي','School MantiqatiX'),('ERP','برمجيات منطقتي','Software MantiqatiX'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX'),('TRIPS','سفر منطقتي','Travel MantiqatiX'),('MANTIGO','نقل منطقتي','Transport MantiqatiX'),('JOBS','وظائف منطقتي','Jobs MantiqatiX'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX'),('AUTO','سيارات منطقتي','Auto MantiqatiX'),('SPORTS','رياضة منطقتي','Sports MantiqatiX'))
insert into public.business_categories(id,sector_id,code,name_ar,name_en,status) select 'CAT-'||code,'SEC-'||code,code,name_ar,name_en,'ACTIVE' from seed
on conflict (id) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,status='ACTIVE';
with seed(code,name_ar,description) as (values ('CONTROL','التحكم الكامل','إدارة الأنشطة والفروع والخدمات والاعتمادات'),('HOME','الرئيسية','لوحة التحكم الموحدة'),('MODULES','الموديولات','تشغيل وإدارة وحدات المنصة'),('DOMAINS','المجالات والخدمات','القطاعات ومقدمو الخدمات'),('FASHION','التجارة والأزياء','المنتجات والمقاسات والسلة والطلبات'),('GROCERY','البقالة والسوبر ماركت','المنتجات والمخزون والطلبات'),('RESTAURANTS','المطاعم والمطابخ','القوائم والإضافات والمطبخ والتوصيل'),('MEDICAL','المنظومة الطبية','الأطباء والعيادات والصيدليات والمعامل والأشعة والمستشفيات'),('MAINTENANCE','الصيانة','طلبات الصيانة ومقدمو الخدمة'),('PRO_SERVICES','الخدمات المهنية','المحاسبة والقانون والشركات والبرمجيات والتسويق'),('MANTIGO','MantiGO والنقل','الطلبات والعروض والرحلات والتنفيذ'),('MATRIMONY','الزواج','الملفات والترشيحات والتواصل'),('JOBS','الوظائف','الوظائف والمتقدمون والمقابلات'),('EDUCATION','التعليم','المدارس والمدرسون والحجوزات'),('USED_ITEMS','المستعمل','الإعلانات والعروض والتفاوض'),('MARKETING','التسويق والإعلان','التسويق الداخلي وشركات التسويق والعملاء المحتملون'),('SMM','خدمات التسويق الرقمي SMM','الخدمات والموردون والطلبات والتتبع'),('CRM','المستخدمون وCRM','العملاء ومقدمو الخدمة والمتابعة والاحتفاظ'),('OPERATIONS','الطلبات والعمليات','الطلبات والحجوزات وسير التنفيذ'),('FINANCE','العمولات والباقات','العمولات والاشتراكات والباقات'),('ANALYTICS','التقارير والتحليلات','الأداء والتحويلات والإيرادات والمخاطر'),('GOVERNANCE','الدعم والحوكمة','التذاكر والتدقيق والصلاحيات والمراقبة'),('REGISTRATION','طلبات التسجيل','اعتماد طلبات العملاء ومقدمي الخدمة'),('SETTINGS','الإعدادات','الحساب والمنصة والتفضيلات'))
insert into public.modules(id,code,name,description,status,version,configuration) select 'MOD-'||code,code,name_ar,description,'ACTIVE','1.0.0','{}'::jsonb from seed
on conflict (id) do update set name=excluded.name,description=excluded.description,status='ACTIVE';
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.businesses(id,tenant_id,organization_id,name,code,status,settings)
select md5('MNTY-SHOWCASE-'||code)::uuid,'MNTY-PLATFORM','MNTY-MAIN',name_ar,'MNTY-'||code,'INACTIVE',
jsonb_build_object('showcase',true,'managed_by','SUPER_ADMIN','brand','MantiqatiX','activity_code',code,'display_name_ar',name_ar,'icon',icon,'icon_asset_ref','assets/activities/'||lower(code)||'.svg','headline',description,'category_code',code,'location_label','منطقتي','profile_complete',true,'source','OFFICIAL_PLATFORM_SHOWCASE')
from seed on conflict (id) do update set name=excluded.name,code=excluded.code,settings=excluded.settings,updated_at=now();
with seed(code) as (values ('HEALTH'),('PHARMACY'),('LABS'),('RADIOLOGY'),('HOSPITAL'),('DENTAL'),('VETERINARY'),('FOOD'),('GROCERY'),('FASHION'),('MAINTENANCE'),('ACCOUNTING'),('LEGAL'),('COMPANIES'),('EDUCATION'),('ERP'),('MARKETING'),('TRIPS'),('MANTIGO'),('JOBS'),('MATRIMONY'),('USED_ITEMS'),('REAL_ESTATE'),('AUTO'),('SPORTS'))
insert into public.user_memberships(id,user_id,tenant_id,organization_id,business_id,branch_id,role,permissions,status)
select 'SHOWCASE-OWNER-'||s.code,'f7914ac7-4b03-4456-afdd-e386f2ac6a5b','MNTY-PLATFORM','MNTY-MAIN',b.id,null,'OWNER','{"showcase_manage":true,"modules_manage":true,"profile_manage":true,"content_manage":true}'::jsonb,'ACTIVE'
from seed s join public.businesses b on b.code='MNTY-'||s.code
on conflict (id) do update set business_id=excluded.business_id,role='OWNER',status='ACTIVE',permissions=excluded.permissions;
update public.businesses b set status='ACTIVE',updated_at=now()
where b.tenant_id='MNTY-PLATFORM' and b.settings->>'showcase'='true' and exists(select 1 from public.user_memberships m where m.business_id=b.id and m.user_id='f7914ac7-4b03-4456-afdd-e386f2ac6a5b'::uuid and m.role in ('OWNER','BUSINESS_OWNER') and m.status='ACTIVE');
with seed(code,name_ar,name_en,icon,description) as (values ('HEALTH','دكتور منطقتي','Doctor MantiqatiX','🩺','خدمات طبية وحجوزات واستشارات'),('PHARMACY','صيدلية منطقتي','Pharmacy MantiqatiX','💊','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','معمل منطقتي','Lab MantiqatiX','🧪','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','أشعة منطقتي','Radiology MantiqatiX','🔬','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','مستشفى منطقتي','Hospital MantiqatiX','🏥','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','أسنان منطقتي','Dental MantiqatiX','🦷','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','بيطري منطقتي','Veterinary MantiqatiX','🐾','رعاية وعلاج وخدمات بيطرية'),('FOOD','مطعم منطقتي','Restaurant MantiqatiX','🍽️','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','سوبر ماركت منطقتي','Supermarket MantiqatiX','🛒','منتجات وبقالة ومخزون وطلبات'),('FASHION','أزياء منطقتي','Fashion MantiqatiX','👗','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','صيانة منطقتي','Maintenance MantiqatiX','🔧','صيانة منزلية وخدمات فنية'),('ACCOUNTING','محاسب منطقتي','Accountant MantiqatiX','🧾','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','محامي منطقتي','Lawyer MantiqatiX','⚖️','استشارات ووثائق وخدمات قانونية'),('COMPANIES','شركة منطقتي','Company MantiqatiX','🏢','خدمات أعمال وموردون وشراكات'),('EDUCATION','مدرسة منطقتي','School MantiqatiX','🎓','تعليم ودروس وتدريب وحجوزات'),('ERP','برمجيات منطقتي','Software MantiqatiX','💻','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','تسويق منطقتي','Marketing MantiqatiX','📣','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','سفر منطقتي','Travel MantiqatiX','✈️','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','نقل منطقتي','Transport MantiqatiX','🚕','نقل وطلبات رحلات وعروض'),('JOBS','وظائف منطقتي','Jobs MantiqatiX','💼','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','زواج منطقتي','Matrimony MantiqatiX','💍','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','مستعمل منطقتي','Used Items MantiqatiX','♻️','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','عقارات منطقتي','Real Estate MantiqatiX','🏠','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','سيارات منطقتي','Auto MantiqatiX','🚗','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','رياضة منطقتي','Sports MantiqatiX','💪','أندية ومدربون وبرامج لياقة'))
insert into public.marketing_provider_profiles(provider_kind,business_id,owner_user_id,name_ar,name_en,slug,description,specialties,service_areas,portfolio,status,is_verified,is_featured,ranking_weight,settings,profile_image_path)
select 'OFFICIAL',b.id,'f7914ac7-4b03-4456-afdd-e386f2ac6a5b',s.name_ar,s.name_en,'mantiqati-'||lower(s.code),s.description,jsonb_build_array(s.description,'حجز وطلب خدمة','متابعة الطلب','خدمة عملاء'),'["منطقتي"]'::jsonb,jsonb_build_array(jsonb_build_object('type','brand_icon','asset','assets/activities/'||lower(s.code)||'.svg','title','هوية '||s.name_ar)),'ACTIVE',true,true,100,jsonb_build_object('official_showcase',true,'managed_by','SUPER_ADMIN','brand','MantiqatiX','icon',s.icon,'location_label','منطقتي'),'assets/activities/'||lower(s.code)||'.svg'
from seed s join public.businesses b on b.code='MNTY-'||s.code
on conflict (slug) do update set business_id=excluded.business_id,owner_user_id=excluded.owner_user_id,name_ar=excluded.name_ar,name_en=excluded.name_en,description=excluded.description,status='ACTIVE',is_verified=true,is_featured=true,ranking_weight=100,settings=excluded.settings,profile_image_path=excluded.profile_image_path;
with seed(code,name_ar,name_en,description) as (values ('HEALTH','خدمة دكتور منطقتي','Doctor MantiqatiX Primary Service','خدمات طبية وحجوزات واستشارات'),('PHARMACY','خدمة صيدلية منطقتي','Pharmacy MantiqatiX Primary Service','منتجات صيدلية وطلبات وخدمة توصيل'),('LABS','خدمة معمل منطقتي','Lab MantiqatiX Primary Service','تحاليل مخبرية وحجز وسحب عينات'),('RADIOLOGY','خدمة أشعة منطقتي','Radiology MantiqatiX Primary Service','خدمات الأشعة والحجز والمتابعة'),('HOSPITAL','خدمة مستشفى منطقتي','Hospital MantiqatiX Primary Service','أقسام طبية وحجوزات وخدمات رعاية'),('DENTAL','خدمة أسنان منطقتي','Dental MantiqatiX Primary Service','كشف وعلاج وتركيبات وتقويم'),('VETERINARY','خدمة بيطري منطقتي','Veterinary MantiqatiX Primary Service','رعاية وعلاج وخدمات بيطرية'),('FOOD','خدمة مطعم منطقتي','Restaurant MantiqatiX Primary Service','قائمة طعام وطلبات وتوصيل وعروض'),('GROCERY','خدمة سوبر ماركت منطقتي','Supermarket MantiqatiX Primary Service','منتجات وبقالة ومخزون وطلبات'),('FASHION','خدمة أزياء منطقتي','Fashion MantiqatiX Primary Service','أزياء ومنتجات وخياطة وطلبات'),('MAINTENANCE','خدمة صيانة منطقتي','Maintenance MantiqatiX Primary Service','صيانة منزلية وخدمات فنية'),('ACCOUNTING','خدمة محاسب منطقتي','Accountant MantiqatiX Primary Service','محاسبة ودفاتر وإقرارات واستشارات مالية'),('LEGAL','خدمة محامي منطقتي','Lawyer MantiqatiX Primary Service','استشارات ووثائق وخدمات قانونية'),('COMPANIES','خدمة شركة منطقتي','Company MantiqatiX Primary Service','خدمات أعمال وموردون وشراكات'),('EDUCATION','خدمة مدرسة منطقتي','School MantiqatiX Primary Service','تعليم ودروس وتدريب وحجوزات'),('ERP','خدمة برمجيات منطقتي','Software MantiqatiX Primary Service','برمجيات ومواقع وأنظمة أعمال'),('MARKETING','خدمة تسويق منطقتي','Marketing MantiqatiX Primary Service','تسويق وإعلان وحملات وإدارة محتوى'),('TRIPS','خدمة سفر منطقتي','Travel MantiqatiX Primary Service','رحلات وحجوزات وبرامج سياحية'),('MANTIGO','خدمة نقل منطقتي','Transport MantiqatiX Primary Service','نقل وطلبات رحلات وعروض'),('JOBS','خدمة وظائف منطقتي','Jobs MantiqatiX Primary Service','وظائف وتوظيف ومتقدمون ومقابلات'),('MATRIMONY','خدمة زواج منطقتي','Matrimony MantiqatiX Primary Service','ملفات وترشيحات وخدمات مرتبطة'),('USED_ITEMS','خدمة مستعمل منطقتي','Used Items MantiqatiX Primary Service','إعلانات مستعمل وعروض وتفاوض'),('REAL_ESTATE','خدمة عقارات منطقتي','Real Estate MantiqatiX Primary Service','بيع وإيجار وإدارة وتسويق عقاري'),('AUTO','خدمة سيارات منطقتي','Auto MantiqatiX Primary Service','سيارات وصيانة وقطع غيار وخدمات نقل'),('SPORTS','خدمة رياضة منطقتي','Sports MantiqatiX Primary Service','أندية ومدربون وبرامج لياقة'))
insert into public.marketing_services(code,name_ar,name_en,category_code,description,status) select 'MNTY_'||code||'_PRIMARY',name_ar,name_en,code,'الخدمة الرسمية الأساسية — '||description,'ACTIVE' from seed
on conflict (code) do update set name_ar=excluded.name_ar,name_en=excluded.name_en,category_code=excluded.category_code,description=excluded.description,status='ACTIVE';
with seed(code) as (values ('HEALTH'),('PHARMACY'),('LABS'),('RADIOLOGY'),('HOSPITAL'),('DENTAL'),('VETERINARY'),('FOOD'),('GROCERY'),('FASHION'),('MAINTENANCE'),('ACCOUNTING'),('LEGAL'),('COMPANIES'),('EDUCATION'),('ERP'),('MARKETING'),('TRIPS'),('MANTIGO'),('JOBS'),('MATRIMONY'),('USED_ITEMS'),('REAL_ESTATE'),('AUTO'),('SPORTS'))
insert into public.marketing_provider_services(provider_id,service_id,service_description,pricing_from,pricing_to,currency,status)
select p.id,s.id,'الخدمة الرسمية الأساسية للنشاط',0,0,'EGP','ACTIVE' from seed x join public.marketing_provider_profiles p on p.slug='mantiqati-'||lower(x.code) join public.marketing_services s on s.code='MNTY_'||x.code||'_PRIMARY'
on conflict (provider_id,service_id) do update set service_description=excluded.service_description,status='ACTIVE';
insert into public.business_modules(id,business_id,module_id,enabled,configuration)
select 'BM-SHOWCASE-'||b.code||'-'||m.code,b.id,m.id,true,jsonb_build_object('managed_by','SUPER_ADMIN','showcase',true,'activity_code',b.settings->>'activity_code')
from public.businesses b cross join public.modules m where b.tenant_id='MNTY-PLATFORM' and b.settings->>'showcase'='true'
on conflict (business_id,module_id) do update set enabled=true,configuration=excluded.configuration,updated_at=now();
drop policy if exists "Public can view official showcase businesses" on public.businesses;
create policy "Public can view official showcase businesses" on public.businesses for select to anon,authenticated using (status='ACTIVE' and coalesce(settings->>'showcase','false')='true');
commit;