const {createClient}=window.supabase;
const cfg=window.MANTIQATIX_CONFIG;
const sb=createClient(cfg.supabaseUrl,cfg.supabaseKey);
const modules=[
['🏠','الرئيسية','لوحة التحكم الموحدة'],['🧩','الموديولات','تشغيل وإدارة وحدات المنصة'],['🏢','المجالات والخدمات','الأطباء والصيدليات والمعامل والمستشفيات وباقي القطاعات'],
['👥','المستخدمون','العملاء ومقدمو الخدمة والموظفون'],['📑','الطلبات','الطلبات والحجوزات ومسارات التنفيذ'],['📣','التسويق والإعلان','التسويق الداخلي وخدمات شركات التسويق'],
['💳','العمولات والباقات','العمولات والاشتراكات والباقات الاحترافية'],['📊','التقارير','تقارير الأداء والمبيعات والعمولات'],['🎫','الدعم','التذاكر والشكاوى وخدمة العملاء'],['⚙️','الإعدادات','الحساب والصلاحيات وإعدادات المنصة']
];
const sectors=[
['🩺','الأطباء والعيادات','ملفات الأطباء، التخصصات، الباقات، الترشيحات والعمولات'],['💊','الصيدليات','الخدمات والمنتجات، الباقات، الطلبات والعمولات'],
['🧪','التحاليل والأشعة','المعامل ومراكز الأشعة، الخدمات، الترشيحات والعمولات'],['🏥','المستشفيات الخاصة','الأقسام والخدمات والباقات والترشيحات'],
['🍽️','المطاعم والكافيهات','الطلبات والعروض وإدارة النشاط'],['🛒','السوبر ماركت','المنتجات والطلبات والعروض'],
['👗','الأزياء','المتاجر والمنتجات والحملات'],['🔧','الصيانة','مقدمو الخدمة والطلبات والترشيحات'],['💼','الأعمال وERP','إدارة الأعمال والمحاسبة والخدمات المهنية'],
['🎓','التعليم','المدارس والمدرسون والخدمات التعليمية'],['✈️','السفر والرحلات','الوكلاء والرحلات والحجوزات'],['🤝','الشركاء','الشركاء الاستراتيجيون ومصادر العملاء']
];
let current='الرئيسية', query='', user=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark=()=>'<span class="mark"></span>';
function authView(msg=''){document.getElementById('app').innerHTML=`<main class="auth"><section class="auth-card"><div class="brand">${mark()}<span>MANTIQATIX</span></div><div class="gradient-line"></div><h1>تسجيل الدخول</h1><p>الوصول إلى منصة MantiqatiX بنفس الحساب والصلاحيات.</p><div class="field"><label>البريد الإلكتروني</label><input id="email" type="email" autocomplete="email" placeholder="name@example.com"></div><div class="field"><label>كلمة المرور</label><input id="password" type="password" autocomplete="current-password" placeholder="••••••••"></div><button class="btn btn-primary" id="login">دخول إلى MantiqatiX</button>${msg?`<div class="msg">${esc(msg)}</div>`:''}</section></main>`;document.getElementById('login').onclick=login}
async function login(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password)return authView('أدخل البريد الإلكتروني وكلمة المرور.');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return authView(error.message);user=data.user;renderApp()}
async function logout(){await sb.auth.signOut();user=null;authView()}
function landingView(){
document.getElementById('app').innerHTML=`<main class="landing">
<header class="landing-nav"><div class="brand">${mark()}<span>MANTIQATIX</span></div><nav><a href="#services">الخدمات</a><a href="#sectors">المجالات</a><a href="#how">كيف تعمل</a><a href="#contact">تواصل معنا</a></nav><button class="btn btn-primary login-open" id="open-login">تسجيل الدخول</button></header>
<section class="landing-hero"><div class="hero-copy"><span class="eyebrow">MANTIQATIX PLATFORM</span><h1>منصة واحدة تربطك <span>بالخدمات والفرص المناسبة</span></h1><p>منصة تسويق وربط تجمع العملاء بمقدمي الخدمات، وتمنح كل مجال نظامًا مستقلًا للباقات والطلبات والترشيحات والعمولات.</p><div class="hero-actions"><button class="btn btn-primary" id="start">استكشف المنصة</button><button class="btn btn-outline" id="provider">انضم كمقدم خدمة</button></div><div class="trust-row"><span>✓ مجالات متعددة</span><span>✓ باقات مرنة</span><span>✓ ترشيحات ذكية</span></div></div><div class="landing-panel"><div class="panel-top"><b>لوحة MantiqatiX</b><span>● نشطة</span></div><div class="panel-stat"><small>الخدمات والمجالات</small><strong>${sectors.length}+</strong></div><div class="panel-grid"><div>🩺<b>أطباء</b></div><div>💊<b>صيدليات</b></div><div>🧪<b>تحاليل وأشعة</b></div><div>🏥<b>مستشفيات</b></div><div>🍽️<b>مطاعم</b></div><div>💼<b>أعمال</b></div></div></div></section>
<section class="landing-section" id="services"><div class="section-head"><div><h2>ماذا تقدم MantiqatiX؟</h2><p>منظومة تسويقية قابلة للتوسع حسب طبيعة كل نشاط.</p></div></div><div class="feature-grid"><article><b>🔗 ربط مباشر</b><p>نساعد العميل على الوصول لمقدم الخدمة، بينما تتم المعاملة المالية مباشرة بين الطرفين.</p></article><article><b>💳 نماذج ربح مرنة</b><p>نظام مجاني، عمولات على العمليات المؤهلة، وباقات احترافية لكل مجال.</p></article><article><b>📣 تسويق وإعلان</b><p>أدوات وحلول تسويقية للشركة وشركاء التسويق ومقدمي الخدمات.</p></article></div></section>
<section class="landing-section" id="sectors"><div class="section-head"><div><h2>مجالات المنصة</h2><p>كل مجال له خدمات ومسارات عمل مناسبة لطبيعته.</p></div></div><div class="sector-strip">${sectors.slice(0,8).map(s=>`<div class="sector-pill"><span>${s[0]}</span>${s[1]}</div>`).join('')}</div></section>
<section class="landing-cta" id="how"><h2>ابدأ من احتياجك</h2><p>عميل يبحث عن خدمة، أو مقدم خدمة يريد عملاء، أو شركة تريد شراكة وتسويقًا أقوى.</p><button class="btn btn-light" id="cta-login">الدخول إلى المنصة</button></section>
<footer id="contact"><div class="brand">${mark()}<span>MANTIQATIX</span></div><span>خدمة العملاء: 01010171770</span></footer>
</main>`;
document.getElementById('open-login').onclick=authView;
document.getElementById('cta-login').onclick=authView;
document.getElementById('start').onclick=()=>document.getElementById('sectors').scrollIntoView({behavior:'smooth'});
document.getElementById('provider').onclick=authView;
}
function filtered(list){const q=query.trim().toLowerCase();return q?list.filter(x=>x.join(' ').toLowerCase().includes(q)):list}
function modulePage(){const list=filtered(modules);return `<div class="section-head"><div><h2>مركز الموديولات</h2><p>تحكم في الوحدات التي تظهر للمنصة والمشتركين.</p></div><span class="count">${list.length} وحدات</span></div><div class="modules">${list.map(m=>`<article class="card module" onclick="selectModule('${m[1]}')"><div class="icon">${m[0]}</div><h3>${m[1]}</h3><div class="muted">${m[2]}</div><span class="status">مفعل</span></article>`).join('')}</div>`}
function sectorsPage(){const list=filtered(sectors);return `<div class="section-head"><div><h2>المجالات والخدمات</h2><p>كل مجال له دورة عمل وباقات وعمولة وترشيحات مناسبة لطبيعته.</p></div></div><div class="modules">${list.map(s=>`<article class="card module"><div class="icon">${s[0]}</div><h3>${s[1]}</h3><div class="muted">${s[2]}</div><div class="mini-actions"><button>فتح المجال</button><button>الباقات</button></div></article>`).join('')}</div>`}
function genericPage(title,desc,items){return `<div class="section-head"><div><h2>${title}</h2><p>${desc}</p></div></div><div class="grid3">${items.map(x=>`<div class="card"><div class="row"><strong>${x[0]}</strong><span class="dot"></span></div><p class="muted">${x[1]}</p><button class="linkbtn">عرض التفاصيل ←</button></div>`).join('')}</div>`}
function dashboard(){return `<section class="hero"><div><span class="eyebrow">MANTIQATIX PLATFORM</span><h2>منصة تسويق وربط الخدمات المحلية</h2><p>وسيط تسويقي يربط العميل بمقدم الخدمة، مع باقات وعمولات ومسارات مستقلة لكل مجال.</p><div class="hero-actions"><button class="btn btn-light" onclick="selectModule('المجالات والخدمات')">استكشف المجالات</button><button class="btn btn-ghost" onclick="selectModule('الموديولات')">إدارة الموديولات</button></div></div></section><section class="cards"><div class="card"><div class="muted">حالة المنصة</div><div class="kpi">نشطة</div><small>Web + Supabase</small></div><div class="card"><div class="muted">المجالات</div><div class="kpi">${sectors.length}</div><small>قطاعات قابلة للتوسع</small></div><div class="card"><div class="muted">الموديولات</div><div class="kpi">${modules.length}</div><small>إدارة مركزية</small></div><div class="card"><div class="muted">خدمة العملاء</div><div class="kpi phone">01010171770</div><small>الدعم والتواصل</small></div></section><div class="section-head"><div><h2>الوصول السريع</h2><p>أهم أجزاء المنصة.</p></div></div><div class="modules">${filtered(modules).slice(0,6).map(m=>`<article class="card module" onclick="selectModule('${m[1]}')"><div class="icon">${m[0]}</div><h3>${m[1]}</h3><div class="muted">${m[2]}</div></article>`).join('')}</div>`}
function pageContent(){switch(current){case'الرئيسية':return dashboard();case'الموديولات':return modulePage();case'المجالات والخدمات':return sectorsPage();case'المستخدمون':return genericPage('المستخدمون','إدارة العملاء ومقدمي الخدمة والموظفين.',[['العملاء','ملفات العملاء وتاريخ الطلبات'],['مقدمو الخدمة','الملفات والاعتماد والباقات'],['الموظفون','الأدوار والصلاحيات']]);case'الطلبات':return genericPage('الطلبات','متابعة الطلبات والحجوزات ومسارات الإحالة.',[['طلبات جديدة','طلبات تحتاج مراجعة'],['قيد المتابعة','طلبات مرتبطة بمقدم خدمة'],['مكتملة','سجل الطلبات المكتملة']]);case'التسويق والإعلان':return genericPage('التسويق والإعلان','نظام التسويق الخاص بالشركة مع إمكانية التعاون مع شركات تسويق أخرى.',[['حملات MantiqatiX','حملات جذب العملاء'],['شركات التسويق','إدارة الشركاء ومصادر العملاء'],['الإعلانات','الحملات والإعلانات الممولة']]);case'العمولات والباقات':return genericPage('العمولات والباقات','نماذج مجانية، عمولة بيع، وباقات احترافية تختلف حسب المجال.',[['الباقة المجانية','وجود أساسي داخل المنصة'],['نظام العمولة','عمولة على العمليات/الإضافات المؤهلة'],['الباقات الاحترافية','3 مستويات قابلة للتخصيص حسب المجال']]);case'التقارير':return genericPage('التقارير','لوحة مؤشرات للإدارة والأداء.',[['الأداء','نشاط المنصة ومقدمي الخدمة'],['الإيرادات','العمولات والباقات'],['التحويلات','مصادر العملاء والطلبات']]);case'الدعم':return genericPage('الدعم','خدمة العملاء والتذاكر والشكاوى.',[['تذاكر مفتوحة','المتابعات الحالية'],['الشكاوى','الملاحظات والحالات'],['مركز المساعدة','الأسئلة والإرشادات']]);default:return genericPage('الإعدادات','إدارة الحساب والمنصة.',[['الحساب','بيانات الحساب وتسجيل الدخول'],['الصلاحيات','الأدوار والوصول'],['إعدادات المنصة','الهوية والإعدادات العامة']])}}
function selectModule(name){current=name;query='';renderApp()}
function renderApp(){document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="side-brand"><div class="brand">${mark()}<span>MANTIQATIX</span></div><div class="gradient-line"></div></div><div class="side-caption">منصة التسويق والربط</div><nav class="nav">${modules.map(m=>`<button class="${m[1]===current?'active':''}" onclick="selectModule('${m[1]}')"><span>${m[0]}</span><span>${m[1]}</span></button>`).join('')}</nav><div class="side-support">خدمة العملاء<br><b>01010171770</b></div></aside><main class="content"><header class="top"><div><div class="breadcrumb">MantiqatiX / ${current}</div><h1>${current}</h1><div class="user" id="user">${esc(user?.email||'')}</div></div><div class="top-actions"><label class="search">⌕ <input id="search" value="${esc(query)}" placeholder="بحث داخل المنصة..."></label><button class="logout" id="logout">خروج</button></div></header><div id="page">${pageContent()}</div></main></div>`;document.getElementById('logout').onclick=logout;const si=document.getElementById('search');si.oninput=e=>{query=e.target.value;document.getElementById('page').innerHTML=pageContent()}}
sb.auth.getSession().then(({data})=>{user=data.session?.user||null;user?renderApp():landingView()});