(function(){
'use strict';
const cfg=window.MANTIQATIX_CONFIG;if(!cfg||!window.supabase)return;const sb=window.MNTY_SB || window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);window.MNTY_SB=sb;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const defs={
'البقالة والسوبر ماركت':{key:'GROCERY',tabs:['overview','catalog','prices'],tables:['catalog_items','catalog_item_prices'],desc:'كتالوج الأصناف والأسعار والطلبات من البنية المركزية.'},
'التسويق والإعلان':{key:'MARKETING',tabs:['overview','providers','services','leads','projects'],tables:['marketing_provider_profiles','marketing_services','marketing_leads','marketing_projects'],desc:'مقدمو خدمات التسويق والخدمات والعملاء والمشروعات.'},
'المزايدات — الخدمات القانونية':{key:'LEGAL',tabs:['overview','documents','requirements','agreements'],tables:['legal_documents','legal_requirements','agreements'],desc:'الوثائق والمتطلبات والاتفاقيات من سجل قانوني مركزي.'},
'المزايدات — الصيانة':{key:'MAINTENANCE',tabs:['overview','requests','support'],tables:['indrive_requests','indrive_bids','support_tickets'],desc:'طلبات الصيانة والعروض والدعم التشغيلي.'}
};
let current=null,rows={},user=null,membership=null,tab='overview',loading=false,error=null;
async function init(){const s=await sb.auth.getSession();user=s.data?.session?.user||null;if(!user)return;const id=localStorage.getItem('MNTYActiveMembershipId');let q=sb.from('user_memberships').select('id,tenant_id,business_id,branch_id,role,status').eq('user_id',user.id).eq('status','ACTIVE');if(id)q=q.eq('id',id);let r=await q.maybeSingle();if(!r.data)r=await sb.from('user_memberships').select('id,tenant_id,business_id,branch_id,role,status').eq('user_id',user.id).eq('status','ACTIVE').limit(1).maybeSingle();membership=r.data||null}
function scope(){return membership?.tenant_id?membership:null}
function canWrite(){return ['OWNER','BUSINESS_OWNER','ADMIN','MANAGER','SERVICE_PROVIDER'].includes(String(membership?.role||'').toUpperCase())}
async function load(d){loading=true;error=null;render();await init();if(!user){error='AUTH_REQUIRED';loading=false;return render()}rows={};for(const t of d.tables){let q=sb.from(t).select('*').limit(150).order('created_at',{ascending:false});if(['catalog_items','catalog_item_prices'].includes(t)&&scope())q=q.eq('tenant_id',scope().tenant_id);if(t==='marketing_leads')q=q.eq('requester_user_id',user.id);if(t==='marketing_projects'&&scope())q=q.eq('client_business_id',scope().business_id);if(t==='support_tickets')q=q.eq('requester_id',user.id);const r=await q;if(r.error)rows[t]=[];else rows[t]=r.data||[]}loading=false;render()}
function shell(d,body){return '<section class="workspace-section"><div class="workspace-head"><div><div class="eyebrow">'+d.key+'</div><h2>'+d.desc+'</h2></div></div>'+body+'</section>'}
function tabs(d){return '<div class="action-bar" style="gap:8px;flex-wrap:wrap">'+d.tabs.map(x=>'<button class="btn '+(tab===x?'btn-primary':'btn-outline')+'" data-op-tab="'+x+'">'+({overview:'نظرة عامة',catalog:'الكتالوج',prices:'الأسعار',providers:'مقدمو الخدمة',services:'الخدمات',leads:'طلبات التسويق',projects:'المشروعات',documents:'الوثائق',requirements:'المتطلبات',agreements:'الاتفاقيات',requests:'طلبات الصيانة',support:'الدعم'}[x]||x)+'</button>').join('')+'</div>'}
function table(h,rs){return '<div class="table-wrap"><table><thead><tr>'+h.map(x=>'<th>'+x[0]+'</th>').join('')+'</tr></thead><tbody>'+(rs.length?rs.map(r=>'<tr>'+h.map(x=>'<td>'+esc(typeof x[1]==='function'?x[1](r):r[x[1]])+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+h.length+'">لا توجد بيانات فعلية ضمن نطاق الصلاحية.</td></tr>')+'</tbody></table></div>'}
function overview(d){return shell(d,tabs(d)+'<div class="cards">'+d.tables.map(t=>'<article class="card"><div class="card-title">'+esc(t)+'</div><div class="metric">'+(rows[t]||[]).length+'</div><div class="muted">سجلات مرئية حاليًا</div></article>').join('')+'</div>')}
function body(d){if(d.key==='GROCERY'){if(tab==='catalog')return shell(d,tabs(d)+table([['الصنف',r=>r.name_ar||r.name_en],['SKU','sku'],['النوع','item_type'],['الحالة','status'],['الوصف','description']],rows.catalog_items||[]));if(tab==='prices')return shell(d,tabs(d)+table([['الصنف','catalog_item_id'],['السعر',r=>money(r.unit_price)],['العملة','currency'],['الإصدار','version'],['الحالة','status'],['يبدأ','effective_from']],rows.catalog_item_prices||[]))}
if(d.key==='MARKETING'){if(tab==='providers')return shell(d,tabs(d)+table([['المقدم',r=>r.name_ar||r.name_en],['النوع','provider_kind'],['الحالة','status'],['موثق',r=>r.is_verified?'نعم':'لا'],['مميز',r=>r.is_featured?'نعم':'لا']],rows.marketing_provider_profiles||[]));if(tab==='services')return shell(d,tabs(d)+table([['الخدمة',r=>r.name_ar||r.name_en],['الكود','code'],['التصنيف','category_code'],['الحالة','status']],rows.marketing_services||[]));if(tab==='leads')return shell(d,tabs(d)+leadForm()+table([['العنوان','title'],['الميزانية',r=>money(r.budget_max)],['المجال','service_area'],['الحالة','status'],['المصدر','source']],rows.marketing_leads||[]));if(tab==='projects')return shell(d,tabs(d)+table([['النوع','project_type'],['الحالة','status'],['القيمة',r=>money(r.gross_value)],['عمولة المنصة',r=>money(r.platform_commission)],['الأجر الإداري',r=>money(r.management_fee)]],rows.marketing_projects||[]))}
if(d.key==='LEGAL'){if(tab==='documents')return shell(d,tabs(d)+table([['العنوان','title'],['النوع','document_type'],['الحالة','status'],['الجمهور',r=>(r.target_audience||[]).join(', ')],['ساري',r=>r.effective_at||'—']],rows.legal_documents||[]));if(tab==='requirements')return shell(d,tabs(d)+table([['الإجراء','action_key'],['الوثيقة','document_type'],['الجمهور','target_audience'],['إلزامي',r=>r.required?'نعم':'لا'],['مفعل',r=>r.enabled?'نعم':'لا']],rows.legal_requirements||[]));if(tab==='agreements')return shell(d,tabs(d)+table([['النوع','agreement_type'],['النشاط','business_id'],['الحالة','status'],['السريان','effective_at']],rows.agreements||[]))}
if(d.key==='MAINTENANCE'){if(tab==='requests')return shell(d,tabs(d)+table([['الطلب','title'],['المجال','category_name'],['الميزانية',r=>money(r.user_proposed_price)],['النطاق','req_location_district'],['الحالة','status']],rows.indrive_requests||[]));if(tab==='support')return shell(d,tabs(d)+table([['الموضوع','subject'],['التصنيف','category'],['الأولوية','priority'],['الحالة','status'],['التاريخ','created_at']],rows.support_tickets||[]))}
return overview(d)}
function leadForm(){return '<div class="card" style="margin:16px 0"><h3>طلب خدمة تسويق</h3><div class="grid-2"><input id="mlTitle" class="input" placeholder="عنوان الطلب"><input id="mlArea" class="input" placeholder="نطاق الخدمة"><input id="mlMin" class="input" type="number" min="0" placeholder="الميزانية من"><input id="mlMax" class="input" type="number" min="0" placeholder="الميزانية إلى"><textarea id="mlDesc" class="input" placeholder="تفاصيل الطلب"></textarea></div><button class="btn btn-primary" id="save-lead">إنشاء طلب</button></div>'}
async function saveLead(){const p={id:crypto.randomUUID(),requester_user_id:user.id,title:document.getElementById('mlTitle').value.trim(),description:document.getElementById('mlDesc').value.trim(),budget_min:Number(document.getElementById('mlMin').value)||0,budget_max:Number(document.getElementById('mlMax').value)||0,currency:'EGP',required_services:[],service_area:document.getElementById('mlArea').value.trim(),status:'OPEN',source:'MNTY'};if(!p.title||!p.description)return alert('أكمل عنوان الطلب والتفاصيل.');if(scope()?.business_id)p.requester_business_id=scope().business_id;const r=await sb.from('marketing_leads').insert(p);if(r.error)return alert(r.error.message);await load(defs[current])}
function render(){const page=document.getElementById('page');if(!page||!current)return;const d=defs[current];if(loading){page.innerHTML=shell(d,tabs(d)+'<p class="muted">جاري تحميل البيانات الفعلية…</p>');return}if(error){page.innerHTML=shell(d,tabs(d)+'<div class="empty-state">'+esc(error)+'</div>');bind();return}page.innerHTML=tab==='overview'?overview(d):body(d);bind()}
function bind(){document.querySelectorAll('[data-op-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.opTab;render()});document.getElementById('save-lead')?.addEventListener('click',saveLead)}
function observe(){const n=document.querySelector('.breadcrumb')?.textContent?.trim()||'';const d=defs[n];if(d&&!current){current=n;tab='overview';load(d)}if(!d)current=null}new MutationObserver(observe).observe(document.body,{childList:true,subtree:true});setInterval(observe,800);
})();