(function(){
'use strict';
const cfg=window.MANTIQATIX_CONFIG;if(!cfg||!window.supabase)return;
const sb=window.MNTY_SB || window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey); window.MNTY_SB=sb;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
const defs={
 'التجارة والأزياء':{key:'FASHION',icon:'🛍️',tables:['fashion_products','fashion_orders','fashion_tailor_services'],title:'التجارة والأزياء',desc:'كتالوج المنتجات والطلبات وخدمات الخياطة.',tabs:['overview','products','orders','tailor']},
 'التعليم':{key:'EDUCATION',icon:'🎓',tables:['school_profiles','teacher_profiles','education_requests'],title:'التعليم',desc:'المدارس والمدرسون وطلبات الخدمات التعليمية.',tabs:['overview','schools','teachers','requests']},
 'الوظائف':{key:'JOBS',icon:'💼',tables:['jobs','job_applications'],title:'الوظائف',desc:'إعلانات الوظائف والتقديمات مع عزل بيانات الأطراف.',tabs:['overview','jobs','applications']},
 'المستعمل':{key:'USED_ITEMS',icon:'♻️',tables:['used_item_ads'],title:'سوق المستعمل',desc:'إعلانات البيع والشراء والبيانات العامة للإعلانات.',tabs:['overview','ads']}
};
let current=null,state={loading:false,error:null,rows:{},tab:'overview',user:null,membership:null};
async function initUser(){const s=await sb.auth.getSession();state.user=s.data?.session?.user||null;if(!state.user)return false;const id=localStorage.getItem('MNTYActiveMembershipId');let q=sb.from('user_memberships').select('id,tenant_id,business_id,branch_id,role,status').eq('user_id',state.user.id).eq('status','ACTIVE');if(id)q=q.eq('id',id);let r=await q.maybeSingle();if(!r.data)r=await sb.from('user_memberships').select('id,tenant_id,business_id,branch_id,role,status').eq('user_id',state.user.id).eq('status','ACTIVE').limit(1).maybeSingle();state.membership=r.data||null;return true}
function canWrite(){return !!state.user&&['OWNER','BUSINESS_OWNER','ADMIN','MANAGER','SERVICE_PROVIDER','STAFF'].includes(String(state.membership?.role||'').toUpperCase())}
function scope(){const m=state.membership;return m?.tenant_id&&m?.business_id?{tenant_id:m.tenant_id,business_id:m.business_id,branch_id:m.branch_id||null}:null}
async function load(d){state.loading=true;state.error=null;render();await initUser();if(!state.user){state.error='AUTH_REQUIRED';state.loading=false;return render()}const s=scope();const r={};for(const t of d.tables){let q=sb.from(t).select('*').order('created_at',{ascending:false}).limit(100);if(['fashion_products','fashion_orders','jobs','used_item_ads'].includes(t)&&s)q=q.eq('tenant_id',s.tenant_id).eq('business_id',s.business_id);if(t==='jobs')q=q.or('is_active.eq.true,owner_user_id.eq.'+state.user.id);if(t==='used_item_ads')q=q.eq('is_sold',false);const x=await q;if(x.error&&t!=='education_requests')r[t]=[];else r[t]=x.data||[]}state.rows=r;state.loading=false;render()}
const DEFAULT_MODULE_IMAGES={FASHION:'assets/module-defaults/fashion.svg',EDUCATION:'assets/module-defaults/education.svg',JOBS:'assets/module-defaults/jobs.svg',USED_ITEMS:'assets/module-defaults/used-items.svg'}; function shell(d,body){const img=DEFAULT_MODULE_IMAGES[d.key]||'';return '<section class="workspace-section"><div class="workspace-head">'+(img?'<img class="module-default-image" src="'+img+'" alt="'+esc(d.title)+'" loading="lazy">':'')+'<div><div class="eyebrow">'+d.key+'</div><h2>'+d.icon+' '+d.title+'</h2><p class="muted">'+d.desc+'</p></div></div>'+body+'</section>'}
function tabs(d){return '<div class="action-bar" style="gap:8px;flex-wrap:wrap">'+d.tabs.map(x=>'<button class="btn '+(state.tab===x?'btn-primary':'btn-outline')+'" data-sector-tab="'+x+'">'+({overview:'نظرة عامة',products:'المنتجات',orders:'الطلبات',tailor:'الخياطة',schools:'المدارس',teachers:'المدرسون',requests:'الطلبات التعليمية',jobs:'الوظائف',applications:'التقديمات',ads:'الإعلانات'}[x]||x)+'</button>').join('')+'</div>'}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+h[0]+'</th>').join('')+'</tr></thead><tbody>'+ (rows.length?rows.map(x=>'<tr>'+headers.map(h=>'<td>'+esc(typeof h[1]==='function'?h[1](x):x[h[1]])+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+headers.length+'">لا توجد بيانات فعلية ضمن النطاق الحالي.</td></tr>')+'</tbody></table></div>'}
function overview(d){const counts=d.tables.map(t=>[t,(state.rows[t]||[]).length,'السجلات المعروضة وفق RLS']);return shell(d,tabs(d)+'<div class="cards">'+counts.map(x=>'<article class="card"><div class="card-title">'+esc(x[0])+'</div><div class="metric">'+x[1]+'</div><div class="muted">'+x[2]+'</div></article>').join('')+'</div><div class="notice" style="margin-top:16px">هذه الصفحة تستخدم البيانات الموجودة فعليًا فقط ولا تنشئ بيانات تجريبية.</div>')}
function view(d){let h='',rows=[];if(d.key==='FASHION'){
 if(state.tab==='products'){rows=state.rows.fashion_products||[];return shell(d,tabs(d)+'<div class="fashion-grid">'+(rows.length?rows.map(r=>'<article class="fashion-card">'+(r.image_url?'<img src="'+esc(r.image_url)+'" alt="'+esc(r.name)+'" loading="lazy">':'<img src="assets/module-defaults/fashion.svg" alt="'+esc(r.name||'منتج')+'" loading="lazy">')+'<div class="fashion-card-body"><span class="eyebrow">'+esc(r.category_name||'أزياء')+'</span><h3>'+esc(r.name||'منتج')+'</h3><p>'+esc(r.description||'')+'</p><strong>'+money(r.price)+'</strong><span class="muted">المخزون: '+esc(r.stock_count)+'</span></div></article>').join(''):'<div class="notice">لا توجد منتجات فعلية ضمن النطاق الحالي.</div>')+'</div>');}
 if(state.tab==='orders'){rows=state.rows.fashion_orders||[];return shell(d,tabs(d)+table([['الطلب','order_id'],['المنتج','product_name'],['المقاس','size'],['الكمية','quantity'],['الإجمالي',r=>money(r.total_price)],['الحالة','status']],rows));}
 if(state.tab==='tailor'){rows=state.rows.fashion_tailor_services||[];return shell(d,tabs(d)+table([['الخدمة','service_type'],['الخياط','tailor_name'],['التقدير',r=>money(r.price_estimate)],['المدة',r=>r.delivery_days+' يوم'],['متاح',r=>r.is_available?'نعم':'لا']],rows));}
}
if(d.key==='EDUCATION'){
 if(state.tab==='schools'){rows=state.rows.school_profiles||[];return shell(d,tabs(d)+'<div class="action-bar">'+rows.map(r=>'<button class="btn btn-primary" style="width:auto" onclick="createEducationRequest(\''+esc(r.id)+'\',\'SCHOOL\',\''+esc(r.available_grades?.[0]||'')+'\')">التقديم</button>').join('')+'</div>'+table([['المدرسة','name'],['النوع','school_type'],['الموقع','location'],['الرسوم',r=>money(r.tuition_fee)],['التقييم','rating']],rows));}
 if(state.tab==='teachers'){rows=state.rows.teacher_profiles||[];return shell(d,tabs(d)+'<div class="action-bar">'+rows.map(r=>'<button class="btn btn-primary" style="width:auto" onclick="createEducationRequest(\''+esc(r.id)+'\',\'TEACHER\',\''+esc(r.subject||'')+'\')">حجز درس</button>').join('')+'</div>'+table([['المدرس','name'],['المادة','subject'],['الأجر/ساعة',r=>money(r.hourly_rate)],['الخبرة',r=>r.experience_years+' سنة'],['التقييم','rating']],rows));}
 if(state.tab==='requests'){rows=state.rows.education_requests||[];return shell(d,tabs(d)+table([['الطلب','id'],['الطالب','student_name'],['المادة/الصف','subject_or_grade'],['النوع','target_type'],['الحالة','status'],['التاريخ','created_at']],rows));}
}
if(d.key==='JOBS'){if(state.tab==='jobs'){rows=state.rows.jobs||[];return shell(d,tabs(d)+'<div class="action-bar">'+rows.map(r=>'<button class="btn btn-primary" style="width:auto" onclick="applyToJob(\''+esc(r.id)+'\')">التقديم للوظيفة</button>').join('')+'</div>'+table([['الوظيفة','title'],['الشركة','company_name'],['التصنيف','category'],['الموقع','location'],['النوع','job_type'],['الراتب','salary_range']],rows));}if(state.tab==='applications'){rows=state.rows.job_applications||[];return shell(d,tabs(d)+table([['الطلب','id'],['الوظيفة','job_id'],['المتقدم','applicant_name'],['المؤهلات','qualifications'],['التاريخ','created_at']],rows));}}
if(d.key==='USED_ITEMS'){rows=state.rows.used_item_ads||[];return shell(d,tabs(d)+'<div class="action-bar">'+rows.map(r=>'<button class="btn '+(r.is_sold?'btn-outline':'btn-primary')+'" style="width:auto" onclick="toggleUsedSold(\''+esc(r.id)+'\','+(r.is_sold?'false':'true')+')">'+(r.is_sold?'إعادة إتاحة':'تسجيل كمباع')+'</button>').join('')+'</div>'+table([['الإعلان','title'],['الفئة','category'],['السعر',r=>money(r.price)],['الموقع','location'],['البائع','seller_name'],['الحالة',r=>r.is_sold?'مباع':'متاح']],rows))}
return overview(d)}
async function createEducationRequest(targetId,targetType,subjectOrGrade){
 if(!state.user?.id||!targetId)return;
 const student=window.prompt('اسم الطالب',state.user.email||'')?.trim();
 if(!student)return;
 const subject=subjectOrGrade||window.prompt(targetType==='TEACHER'?'المادة':'الصف الدراسي','')?.trim();
 if(!subject)return;
 const r=await sb.from('education_requests').insert({id:crypto.randomUUID(),requester_user_id:state.user.id,target_id:targetId,target_type:targetType,student_name:student,subject_or_grade:subject,status:'PENDING'});
 if(r.error)return alert('تعذر إرسال الطلب: '+r.error.message);
 alert('تم إرسال الطلب التعليمي بنجاح.');
 await load(defs[current]);
}
function form(d){if(d.key==='EDUCATION'&&state.tab==='schools'&&state.user)return '<div class="card" style="margin-top:16px"><h3>التقديم إلى مدرسة</h3><p class="muted">اختر المدرسة من القائمة ثم استخدم زر التقديم.</p></div>';if(d.key==='EDUCATION'&&state.tab==='teachers'&&state.user)return '<div class="card" style="margin-top:16px"><h3>حجز درس</h3><p class="muted">يمكن إرسال طلب درس من زر الحجز بجوار المعلم.</p></div>';if(!canWrite())return '';if(d.key==='JOBS'&&state.tab==='jobs')return '<div class="card" style="margin-top:16px"><h3>إضافة وظيفة</h3><div class="grid-2"><input id="jTitle" class="input" placeholder="المسمى الوظيفي"><input id="jCompany" class="input" placeholder="اسم الشركة"><input id="jCategory" class="input" placeholder="التصنيف"><input id="jLocation" class="input" placeholder="الموقع"><input id="jType" class="input" placeholder="نوع الوظيفة"><input id="jSalary" class="input" placeholder="نطاق الراتب"><textarea id="jDesc" class="input" placeholder="الوصف"></textarea></div><button class="btn btn-primary" id="save-job">حفظ الوظيفة</button></div>';if(d.key==='USED_ITEMS'&&state.tab==='ads')return '<div class="card" style="margin-top:16px"><h3>إضافة إعلان</h3><div class="grid-2"><input id="uTitle" class="input" placeholder="عنوان الإعلان"><input id="uCategory" class="input" placeholder="الفئة"><input id="uPrice" class="input" type="number" min="0" placeholder="السعر"><input id="uLocation" class="input" placeholder="الموقع"><textarea id="uDesc" class="input" placeholder="الوصف"></textarea></div><button class="btn btn-primary" id="save-used">حفظ الإعلان</button></div>';if(d.key==='FASHION'&&state.tab==='products')return '<div class="card" style="margin-top:16px"><h3>إضافة منتج</h3><div class="grid-2"><input id="fName" class="input" placeholder="اسم المنتج"><input id="fCat" class="input" placeholder="الفئة"><input id="fPrice" class="input" type="number" min="0" placeholder="السعر"><input id="fStock" class="input" type="number" min="0" placeholder="المخزون"><input id="fStore" class="input" placeholder="اسم المتجر"><textarea id="fDesc" class="input" placeholder="الوصف"></textarea></div><button class="btn btn-primary" id="save-fashion">حفظ المنتج</button></div>';return ''}
async function applyToJob(jobId){if(!state.user?.id||!jobId)return;const name=window.prompt('اسم المتقدم',state.user.email||'')?.trim();if(!name)return;const phone=window.prompt('رقم الهاتف (اختياري)','')?.trim()||'';const qualifications=window.prompt('المؤهلات والخبرات','')?.trim()||'';const cv=window.prompt('ملخص السيرة الذاتية (اختياري)','')?.trim()||'';const r=await sb.from('job_applications').insert({id:crypto.randomUUID(),job_id:jobId,applicant_user_id:state.user.id,applicant_name:name,applicant_phone:phone,qualifications,cv_summary_text:cv});if(r.error)return alert('تعذر إرسال طلب التوظيف: '+r.error.message);alert('تم إرسال طلب التوظيف.');await load(defs[current])}
async function applyToJob(jobId,jobTitle){
 if(!state.user?.id)return alert('يجب تسجيل الدخول.');
 const applicantName=window.prompt('اسم المتقدم',state.user.email||'')?.trim();
 if(!applicantName)return;
 const phone=window.prompt('رقم الهاتف')?.trim()||'';
 const qualifications=window.prompt('المؤهلات')?.trim()||'';
 const cv=window.prompt('ملخص السيرة الذاتية')?.trim()||'';
 const r=await sb.from('job_applications').insert({id:crypto.randomUUID(),job_id:jobId,applicant_user_id:state.user.id,applicant_name:applicantName,applicant_phone:phone,qualifications,cv_summary_text:cv});
 if(r.error)return alert('تعذر إرسال طلب الوظيفة: '+r.error.message);
 alert('تم إرسال طلب التوظيف.');
 await load(defs[current]);
}
async function saveJob(){const s=scope();if(!s)return alert('اختر عضوية نشاط نشطة.');const id=crypto.randomUUID();const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)return alert('انتهت الجلسة، سجل الدخول مجددًا.');const payload={p_user_id:state.user.id,p_job_id:id,p_tenant_id:s.tenant_id,p_business_id:s.business_id,p_title:document.getElementById('jTitle').value.trim(),p_company_name:document.getElementById('jCompany').value.trim(),p_category:document.getElementById('jCategory').value.trim(),p_location:document.getElementById('jLocation').value.trim(),p_job_type:document.getElementById('jType').value.trim(),p_salary_range:document.getElementById('jSalary').value.trim(),p_description:document.getElementById('jDesc').value.trim(),p_requirements:''};const r=await sb.rpc('create_job_backend',payload);if(r.error)return alert(r.error.message);await load(defs[current])}
async function saveUsed(){const s=scope();if(!s)return alert('اختر عضوية نشاط نشطة.');const p={id:crypto.randomUUID(),owner_user_id:state.user.id,tenant_id:s.tenant_id,business_id:s.business_id,title:document.getElementById('uTitle').value.trim(),category:document.getElementById('uCategory').value.trim(),price:Number(document.getElementById('uPrice').value),location:document.getElementById('uLocation').value.trim(),description:document.getElementById('uDesc').value.trim(),seller_name:state.user.email||'',seller_phone:'',is_sold:false,fee_paid:0};if(!p.title||!p.category||!Number.isFinite(p.price)||p.price<0)return alert('أكمل بيانات الإعلان.');const r=await sb.from('used_item_ads').insert(p);if(r.error)return alert(r.error.message);await load(defs[current])}
async function toggleUsedSold(id,isSold){
 if(!state.user?.id)return alert('يجب تسجيل الدخول.');
 const r=await sb.from('used_item_ads').update({is_sold:isSold}).eq('id',id).eq('owner_user_id',state.user.id);
 if(r.error)return alert('تعذر تحديث حالة الإعلان: '+r.error.message);
 await load(defs[current]);
}
async function saveFashion(){const s=scope();if(!s)return alert('اختر عضوية نشاط نشطة.');const p={id:crypto.randomUUID(),owner_user_id:state.user.id,tenant_id:s.tenant_id,business_id:s.business_id,branch_id:s.branch_id||'',name:document.getElementById('fName').value.trim(),category_name:document.getElementById('fCat').value.trim(),price:Number(document.getElementById('fPrice').value),stock_count:Number(document.getElementById('fStock').value),store_name:document.getElementById('fStore').value.trim(),description:document.getElementById('fDesc').value.trim(),rating:0,review_count:0,original_price:null,image_url:'',available_sizes:[],available_colors:[],is_best_seller:false,is_new_arrival:true};if(!p.name||!p.category_name||!Number.isFinite(p.price)||p.price<0||!Number.isInteger(p.stock_count)||p.stock_count<0)return alert('تحقق من بيانات المنتج.');const r=await sb.from('fashion_products').insert(p);if(r.error)return alert(r.error.message);await load(defs[current])}
function render(){if(!current)return;const page=document.getElementById('page');if(!page)return;const d=defs[current];if(!d)return;if(state.loading){page.innerHTML=shell(d,tabs(d)+'<p class="muted">جاري تحميل البيانات الفعلية…</p>');return}if(state.error){page.innerHTML=shell(d,tabs(d)+'<div class="empty-state">'+esc(state.error)+'</div>');bind();return}page.innerHTML=(state.tab==='overview'?overview(d):view(d))+form(d);bind()}
function bind(){document.querySelectorAll('[data-sector-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.sectorTab;render()});document.getElementById('save-job')?.addEventListener('click',saveJob);document.getElementById('save-used')?.addEventListener('click',saveUsed);document.getElementById('save-fashion')?.addEventListener('click',saveFashion)}
function observe(){const b=document.querySelector('.breadcrumb');const name=b?.textContent?.trim()||'';const d=defs[name];if(d&&!current){current=name;state.tab='overview';load(d)}else if(!d&&current){current=null} }
new MutationObserver(observe).observe(document.body,{childList:true,subtree:true});setInterval(observe,800);
})();