const {createClient}=window.supabase;const cfg=window.MANTIQATIX_CONFIG;const sb=createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true,flowType:'pkce'}});const FN=cfg.supabaseUrl+'/functions/v1/smm-gateway';let user=null,services=[],orders=[],wallet=0,isAdmin=false,tab='services',selected=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>Number(n||0).toFixed(4);
async function fn(body){const {data:{session}}=await sb.auth.getSession();const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':cfg.supabaseKey},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||'حدث خطأ');return d}
async function load(){
 const {data:{session}}=await sb.auth.getSession();
 user=session?.user||null;
 if(!user)return renderAuth();
 try{
  const [catalog,account]=await Promise.all([fn({action:'catalog'}),fn({action:'my_data'})]);
  services=Array.isArray(catalog.services)?catalog.services:[];
  orders=Array.isArray(account.orders)?account.orders:[];
  wallet=Number(account.balance);
  if(!Number.isFinite(wallet))throw new Error('INVALID_WALLET_RESPONSE');
  isAdmin=account.is_admin===true;
  render();
 }catch(error){
  console.warn('[MNTY SMM] trusted read gateway unavailable',error?.message||'READ_FAILED');
  renderReadError();
 }
}
function renderReadError(){
 document.getElementById('app').innerHTML='<div class="app"><header class="top"><div class="brand"><span class="logo">M</span>MantiqatiX SMM</div><button class="btn outline" id="read-retry">إعادة المحاولة</button></header><main class="wrap"><section class="card"><h2>بيانات خدمات التسويق غير متاحة حاليًا</h2><p class="muted">تعذر تحميل الكتالوج أو بيانات الحساب من الخادم. لم نعرض قائمة خدمات فارغة أو رصيدًا صفريًا على أنهما بيانات مؤكدة.</p><button class="btn primary" id="read-retry-main">إعادة المحاولة</button></section></main></div>';
 document.getElementById('read-retry').onclick=load;
 document.getElementById('read-retry-main').onclick=load;
}
function renderAuth(){document.getElementById('app').innerHTML='<div class="modal"><div><div class="brand"><span class="logo">M</span>MantiqatiX SMM</div><h2 id="at">تسجيل الدخول</h2><p class="muted">استخدم حساب Google للدخول إلى خدمات MantiqatiX SMM. ستعود إلى هذه الصفحة بعد التحقق من هويتك.</p><div id="am"></div><div class="form"><button class="btn primary" id="google-auth" type="button">🔐 الدخول بحساب Google</button><a class="btn outline" href="./">العودة إلى MantiqatiX</a></div></div></div>';document.getElementById('google-auth').onclick=async()=>{const btn=document.getElementById('google-auth');btn.disabled=true;document.getElementById('am').innerHTML='<div class="notice">جاري تحويلك إلى Google للتحقق من الهوية...</div>';const redirectTo=window.location.origin+window.location.pathname;const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo,queryParams:{access_type:'online',prompt:'select_account'}}});if(r.error){btn.disabled=false;document.getElementById('am').innerHTML='<div class="notice">'+esc(r.error.message)+'</div>';}}}
function render(){document.getElementById('app').innerHTML='<div class="app"><header class="top"><div class="brand"><span class="logo">M</span>MantiqaTix SMM</div><div class="top-actions"><span class="small">'+esc(user.email)+'</span><button class="btn outline" id="logout">خروج</button></div></header><main class="wrap"><section class="hero"><div><span class="badge">SMM WHOLESALE ENGINE</span><h1>بيع الخدمات الرقمية تحت علامتك</h1><p>واجهة مستقلة، كتالوج خدمات، رصيد، طلبات، ومتابعة حالة التنفيذ. الربط بالمزود يتم من الخادم ولا يظهر مفتاح الـAPI للعميل.</p></div><div class="stats"><div class="stat"><small>رصيدك</small><strong>$'+money(wallet)+'</strong></div><div class="stat"><small>الخدمات</small><strong>'+services.length+'</strong></div><div class="stat"><small>طلباتك</small><strong>'+orders.length+'</strong></div></div></section><div class="tabs"><button class="tab '+(tab==='services'?'active':'')+'" data-tab="services">الخدمات</button><button class="tab '+(tab==='orders'?'active':'')+'" data-tab="orders">طلباتي</button>'+(isAdmin?'<button class="tab '+(tab==='admin'?'active':'')+'" data-tab="admin">لوحة الإدارة</button>':'')+'</div><section id="view"></section></main></div>';document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.getElementById('logout').onclick=async()=>{await sb.auth.signOut();user=null;renderAuth()};drawView()}
function drawView(){const v=document.getElementById('view');if(tab==='services'){v.innerHTML='<div class="card"><div class="form"><input class="input" id="filter" placeholder="ابحث عن Instagram / TikTok / YouTube / الخدمة..."></div></div><div class="grid" id="services"></div>';drawServices();document.getElementById('filter').oninput=drawServices;}else if(tab==='orders')drawOrders(v);else drawAdmin(v)}
function drawServices(){const q=(document.getElementById('filter')?.value||'').toLowerCase();const list=services.filter(s=>(s.name+' '+s.platform+' '+s.category).toLowerCase().includes(q));document.getElementById('services').innerHTML=list.map(s=>'<article class="card service" data-id="'+s.id+'"><span class="badge">'+esc(s.platform)+'</span><h3>'+esc(s.name)+'</h3><div class="muted">'+esc(s.category)+'</div><div class="price">$'+money(s.selling_price)+' <span class="small">/ 1000</span></div><div class="muted">الحد: '+s.min_quantity+' — '+s.max_quantity+' | Refill: '+(s.refill?'نعم':'لا')+'</div><button class="btn primary" style="margin-top:12px">اطلب الخدمة</button></article>').join('')||'<div class="card">لا توجد خدمات منشورة بعد. لوحة الإدارة تحتاج مزودًا متصلًا ومزامنة الخدمات.</div>';document.querySelectorAll('.service').forEach(x=>x.onclick=()=>openOrder(x.dataset.id))}
function openOrder(id){selected=services.find(x=>x.id===id);const m=document.createElement('div');m.className='modal';m.innerHTML='<div><h2>'+esc(selected.name)+'</h2><p class="muted">سعر البيع: $'+money(selected.selling_price)+' لكل 1000</p><div class="form"><input class="input" id="target" placeholder="الرابط / الحساب المستهدف"><input class="input" id="qty" type="number" value="'+selected.min_quantity+'" min="'+selected.min_quantity+'" max="'+selected.max_quantity+'"><button class="btn primary" id="place">تنفيذ الطلب</button><button class="btn outline" id="close">إلغاء</button></div><div id="om"></div></div>';document.body.appendChild(m);m.querySelector('#close').onclick=()=>m.remove();m.querySelector('#place').onclick=async()=>{const target=m.querySelector('#target').value.trim(),qty=Number(m.querySelector('#qty').value);if(!target||qty<selected.min_quantity||qty>selected.max_quantity)return m.querySelector('#om').innerHTML='<div class="notice">تحقق من الرابط والكمية.</div>';try{const r=await fn({action:'place_order',service_id:selected.id,target_url:target,quantity:qty});m.querySelector('#om').innerHTML='<div class="notice success">تم إرسال الطلب. رقم الطلب: '+esc(r.order_id)+'<br>Provider order: '+esc(r.provider_order_id||'—')+'</div>';setTimeout(()=>{m.remove();load()},1200)}catch(e){m.querySelector('#om').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}}
function drawOrders(v){v.innerHTML='<div class="card"><h2>طلباتي</h2><table class="table"><thead><tr><th>التاريخ</th><th>الكمية</th><th>السعر</th><th>الحالة</th><th>المزود</th><th></th></tr></thead><tbody>'+orders.map(o=>'<tr><td>'+new Date(o.created_at).toLocaleString('ar-EG')+'</td><td>'+o.quantity+'</td><td>$'+money(o.selling_price)+'</td><td><span class="pill '+o.status+'">'+esc(o.status)+'</span></td><td>'+esc(o.provider_order_id||'—')+'</td><td><button class="btn outline" onclick="syncOrder(\''+o.id+'\')">تحديث</button></td></tr>').join('')+'</tbody></table></div>'}
async function syncOrder(id){try{await fn({action:'order_status',order_id:id});load()}catch(e){alert(e.message)}}
async function drawAdmin(v){v.innerHTML='<div class="admin-grid"><div class="card"><h2>الموردون</h2><div id="providers">جارٍ التحميل...</div></div><div class="card"><h2>شحن رصيد مستخدم</h2><div class="form"><input class="input" id="uid" placeholder="User ID"><input class="input" id="amount" type="number" step="0.01" placeholder="المبلغ USD"><input class="input" id="desc" placeholder="الوصف"><button class="btn primary" id="credit">إضافة الرصيد</button><div id="cm"></div></div></div></div><div class="card admin"><h2>آخر الخدمات</h2><div id="adm-services">جارٍ التحميل...</div></div><div class="card admin"><h2>آخر الطلبات</h2><div id="adm-orders">جارٍ التحميل...</div></div>';try{const d=await fn({action:'admin_data'});document.getElementById('providers').innerHTML=d.providers.map(p=>'<div class="provider-row"><div><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.api_url)+'</div></div><div><button class="btn outline" onclick="configProvider(\''+p.id+'\',\''+esc(p.name)+'\')">API Key</button><button class="btn outline" onclick="syncProvider(\''+p.id+'\')">Sync</button></div></div>').join('');document.getElementById('adm-services').innerHTML='<table class="table"><tr><th>الخدمة</th><th>التكلفة</th><th>سعر البيع</th><th>تعديل</th></tr>'+d.services.slice(0,50).map(s=>'<tr><td>'+esc(s.name)+'</td><td>$'+money(s.provider_cost)+'</td><td><input class="input" id="p'+s.id+'" value="'+s.selling_price+'"></td><td><button class="btn outline" onclick="setPrice(\''+s.id+'\')">حفظ</button></td></tr>').join('')+'</table>';document.getElementById('adm-orders').innerHTML='<table class="table"><tr><th>التاريخ</th><th>المستخدم</th><th>المبلغ</th><th>الربح</th><th>الحالة</th></tr>'+d.orders.map(o=>'<tr><td>'+new Date(o.created_at).toLocaleString('ar-EG')+'</td><td>'+esc(o.user_id)+'</td><td>$'+money(o.selling_price)+'</td><td>$'+money(o.profit)+'</td><td>'+esc(o.status)+'</td></tr>').join('')+'</table>';}catch(e){v.innerHTML+='<div class="notice">'+esc(e.message)+'</div>'}document.getElementById('credit').onclick=async()=>{try{await fn({action:'admin_credit',user_id:document.getElementById('uid').value,amount:Number(document.getElementById('amount').value),description:document.getElementById('desc').value});document.getElementById('cm').innerHTML='<div class="notice success">تم إضافة الرصيد.</div>'}catch(e){document.getElementById('cm').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}}
async function configProvider(id,name){const key=prompt('أدخل API Key للمزود '+name+' — لن يظهر المفتاح في قاعدة البيانات المكشوفة.');if(!key)return;try{await fn({action:'configure_provider',provider_id:id,api_key:key});alert('تم حفظ مفتاح المزود وتفعيله.');}catch(e){alert(e.message)}}
async function syncProvider(id){try{const r=await fn({action:'sync_services',provider_id:id});alert('تمت مزامنة '+r.count+' خدمة.');load()}catch(e){alert(e.message)}}
async function setPrice(id){const val=document.getElementById('p'+id).value;try{await fn({action:'set_price',service_id:id,selling_price:Number(val)});alert('تم حفظ السعر.');}catch(e){alert(e.message)}}
sb.auth.onAuthStateChange(()=>load());load();